// <editor-fold defaultstate="collapsed" desc="Description/Instruction ">
/**
 * @file pfc.c
 *
 * @brief This module has functions required for Power Factor Correction Control
 */
// </editor-fold>

// <editor-fold defaultstate="collapsed" desc="Disclaimer ">

/*******************************************************************************
* SOFTWARE LICENSE AGREEMENT
* 
* � [2024] Microchip Technology Inc. and its subsidiaries
* 
* Subject to your compliance with these terms, you may use this Microchip 
* software and any derivatives exclusively with Microchip products. 
* You are responsible for complying with third party license terms applicable to
* your use of third party software (including open source software) that may 
* accompany this Microchip software.
* 
* Redistribution of this Microchip software in source or binary form is allowed 
* and must include the above terms of use and the following disclaimer with the
* distribution and accompanying materials.
* 
* SOFTWARE IS "AS IS." NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY,
* APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,
* MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT WILL 
* MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR 
* CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND WHATSOEVER RELATED TO
* THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS BEEN ADVISED OF THE 
* POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY
* LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL
* NOT EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR THIS
* SOFTWARE
*
* You agree that you are solely responsible for testing the code and
* determining its suitability.  Microchip has no obligation to modify, test,
* certify, or support the code.
*
*******************************************************************************/
// </editor-fold>

// <editor-fold defaultstate="collapsed" desc="HEADER FILES ">
    
#ifdef __XC16__  // See comments at the top of this header file
    #include <xc.h>
#endif // __XC16__

#include <stdint.h>
#include <stdbool.h>
#include <math.h>       /* sqrtf, for the DCM branch of the duty feed-forward */
#include "libq.h"
#include "pfc.h"
#include "pfc_calc_params.h"
#include "board_service.h"
#include "diagnostics.h"

// </editor-fold> 

// <editor-fold defaultstate="collapsed" desc="Function Declarations ">

static float PFC_SignalRectification(PFC_MEASURE_VOLTAGE_T *);
static float PFC_DcmAverageFactor(PFC_T *);
static float PFC_DutyFeedForward(PFC_T *);
static uint16_t PFC_ConductionModeDetect(PFC_T *);
static void PFC_CurrentSampleCorrection(PFC_T *);
static void PFC_Average(PFC_AVG_T *,float);
static void PFC_SquaredRMSCalculate(PFC_RMS_SQUARE_T *,float);
static void PFC_VdcFilterReset(PFC_VDC_NOTCH_T *,float);
inline static void PFC_VdcFilterUpdate(PFC_T *);

inline static void PFC_CurrentRefGenerate(PFC_T *);
inline static void PFC_CurrentControlLoop(PFC_T *);
static void PFC_CurrentPILimitsUpdate(PFC_T *);

static void PFC_ParamsInit(PFC_T *);
static void PFC_ResetParams(PFC_T *);
static void PFC_FaultCheck(PFC_T *);
void PFC_StateMachine(PFC_T *);

inline static void PFC_UpdateMeasurements(PFC_T *);
inline static void PFC_UpdateCurrentFeedback(PFC_T *);
inline static void PFC_SoftStartUpdate(PFC_T *);
inline static void PFC_UpdateBoostDutyRatio(PFC_T *);
inline static void PFC_BurstModeUpdate(PFC_T *);

static PFC_CTRL_STATE_T PFC_StateInit(PFC_T *);
static PFC_CTRL_STATE_T PFC_StatePrecharge(PFC_T *);
static PFC_CTRL_STATE_T PFC_StateOffsetMeas(PFC_T *);
static PFC_CTRL_STATE_T PFC_StateWait1Cycle(PFC_T *);
static PFC_CTRL_STATE_T PFC_StateCtrlRun(PFC_T *);
static PFC_CTRL_STATE_T PFC_StateFault(PFC_T *);

// </editor-fold> 

// <editor-fold defaultstate="collapsed" desc="Global Variables  ">

PFC_T pfcParam;
uint16_t counter = 0;

// </editor-fold>

// <editor-fold defaultstate="collapsed" desc="INTERFACE FUNCTIONS ">
/**
* <B> Function: PFC_ADCInterrupt()  </B>
*
* @brief ADC interrupt vector ,and it performs following actions:
*        (1) Reads DC BUS voltage,input AC voltage and inductor current feedback 
*            from ADC data buffers.
*        (2) Executes Power Factor Correction State machine
*        (3) Loads duty cycle value generated by PFC current control loop to 
*            PWM Duty Register
*        (4) Executes the DiagnosticsStepIsr() for Data visualization 
*            through X2C Scope
*/
void __attribute__((__interrupt__,no_auto_psv)) PFC_ADCInterrupt()
{    
    /** Load ADC Buffer data to respective variables */
    pfcParam.pfcVoltage.outputVoltage       = ADCBUF_VDC>>1;
    pfcParam.pfcVoltage.acVoltage           = ADCBUF_PFC_VAC;
    pfcParam.pfcCurrent.inductorCurrent     = ADCBUF_PFC_IL;
    pfcParam.pfcCurrent2.inductorCurrent    = ADCBUF_PFC_IL2;
    
    pfcParam.pfcVoltage.vdc  = (float)(pfcParam.pfcVoltage.outputVoltage*ADC_VOLTAGE_SCALE);
    pfcParam.pfcVoltage.vac  = (float)(pfcParam.pfcVoltage.acVoltage*ADC_VOLTAGE_SCALE);
    pfcParam.pfcCurrent.iL   = (float)(pfcParam.pfcCurrent.inductorCurrent*ADC_CURRENT_SCALE);
    pfcParam.pfcCurrent2.iL  = (float)(pfcParam.pfcCurrent2.inductorCurrent*ADC_CURRENT_SCALE);

    /** Load-current feed-forward input: same IL2 sample, load-sensor scale. */
    pfcParam.loadFF.rawADC   = pfcParam.pfcCurrent2.inductorCurrent;
    pfcParam.loadFF.current  = (float)(pfcParam.loadFF.rawADC * pfcParam.loadFF.scale);
    
    
    PFC_StateMachine(&pfcParam);

#ifdef DEBUG_BOOST
    PFC_ENABLE_SIGNAL = 1;
    pfcParam.duty  = DEBUG_PFC_DUTY;
#endif
    
    PFC_PWM_PDC = pfcParam.duty;  
    #ifdef ENABLE_DIAGNOSTICS
    if (counter < (PFC_DIAGNOSTICS_DECIMATION - 1))
    {
        counter++;
    }
    else
    {
        DiagnosticsStepIsr();
        counter = 0;
    }
    #endif

    ClearPFCADCIF();
}
/**
 * <B> Function: PFC_StateMachine(PFC_T *pfcData)  </B>
 * @brief Function to perform  - VAC RMS calculation, calculate moving average 
 *        of Vdc, PFC voltage control loop,  generate current reference, PFC  
 *        current control loop.
 * @param none.
 * @return none.
 * @example
 * <code>
 * status = PFC_StateMachine();
 * </code>
 */
void PFC_StateMachine(PFC_T *pfcData)
{
    PFC_CTRL_STATE_T pfcState = pfcData->state;

    /** Per-ISR signal conditioning, run in every state. */
    PFC_UpdateMeasurements(pfcData);

    switch(pfcState)
    {
        case PFC_INIT:        pfcState = PFC_StateInit(pfcData);       break;
        case PFC_PRECHARGE:   pfcState = PFC_StatePrecharge(pfcData);  break;
        case PFC_OFFSET_MEAS: pfcState = PFC_StateOffsetMeas(pfcData); break;
        case PFC_WAIT_1CYCLE: pfcState = PFC_StateWait1Cycle(pfcData); break;
        case PFC_CTRL_RUN:    pfcState = PFC_StateCtrlRun(pfcData);    break;
        case PFC_FAULT:       pfcState = PFC_StateFault(pfcData);      break;
        default:                                                       break;
    }

    pfcData->state = pfcState;
}
/**
 * <B> Function: PFC_UpdateMeasurements(PFC_T *pfcData) </B>
 * @brief Per-ISR signal conditioning that runs in every state: moving averages
 *        of Vdc and Vac, the AC offset, rectification, the RMS-square of Vac,
 *        and the load-current feed-forward term.
 */
inline static void PFC_UpdateMeasurements(PFC_T *pfcData)
{
    PFC_MEASURE_VOLTAGE_T *pVoltage = &pfcData->pfcVoltage;

    /** Average of PFC output (DC) voltage over one 100 Hz ripple period
        (nulls the double-line ripple - see PFC_VDC_AVG_SAMPLES). */
    PFC_Average(&pfcData->vdcAVG, pVoltage->vdc);
    pfcData->outputVdc = pfcData->vdcAVG.output;

    /** Notch + anti-noise pole on the same measurement, feeding the voltage PI
        only. Updated in every state and whether or not it is enabled, so it
        can be observed in X2C before being switched in - same idea as loadFF.
        Must follow PFC_Average: the disabled path falls back to its output. */
    PFC_VdcFilterUpdate(pfcData);

    /** Load-current feed-forward: low-pass the measured load current and form
        the feed-forward power (gain * Vdc * I_load). Injected into the voltage-
        loop power command in PFC_CurrentRefGenerate only when loadFF.enable is
        set, but computed every ISR and always (so it can be observed in X2C
        before enabling). Averaged Vdc avoids injecting bus ripple. */
    pfcData->loadFF.currentFilt += (pfcData->loadFF.current - pfcData->loadFF.currentFilt) * pfcData->loadFF.filtCoeff;
    pfcData->loadFF.powerFF = pfcData->loadFF.gain * pfcData->outputVdc * pfcData->loadFF.currentFilt;

    /** Average of input AC voltage feedback (used as the AC offset). */
    PFC_Average(&pfcData->vacAVG, pVoltage->vac);
    pVoltage->offsetVac = pfcData->vacAVG.output;

    /** Rectify the input AC voltage. */
    pfcData->rectifiedVac = PFC_SignalRectification(pVoltage);

    /** RMS-square of the rectified input voltage. */
    PFC_SquaredRMSCalculate(&pfcData->vacRMS, pfcData->rectifiedVac);
}
/**
 * <B> Function: PFC_VdcFilterReset(PFC_VDC_NOTCH_T *pNotch, float value) </B>
 * @brief Preload every filter state so the chain starts already settled at
 *        value, instead of charging up from zero when control is handed over.
 *        Valid as a fixed point because the DC gain is exactly 1: substituting
 *        x1=x2=y1=y2=v into the difference equation returns v.
 */
static void PFC_VdcFilterReset(PFC_VDC_NOTCH_T *pNotch, float value)
{
    pNotch->lpfOut  = value;
    pNotch->x1      = value;
    pNotch->x2      = value;
    pNotch->y1      = value;
    pNotch->y2      = value;
    pNotch->output  = value;
    pNotch->exeRate = 0;
}
/**
 * <B> Function: PFC_VdcFilterUpdate(PFC_T *pfcData) </B>
 * @brief Anti-noise pole followed by the 100 Hz notch, run at the voltage-loop
 *        rate, and selection of the signal the voltage PI closes on.
 */
inline static void PFC_VdcFilterUpdate(PFC_T *pfcData)
{
    PFC_VDC_NOTCH_T *pNotch = &pfcData->vdcNotch;

    /* Decimate to the voltage-loop rate. Running the biquad at the full ISR
       rate instead would place its poles at a radius of ~0.995, where float32
       cancellation against the ~380 V DC pedestal limits the achievable null
       to roughly -33 dB and throws away most of the benefit. This counter is
       independent of voltLoopExeRate (which only advances in PFC_CTRL_RUN), so
       the two run at the same rate with a constant offset of at most one ISR -
       187.5 us, 0.4 deg at crossover, already inside the design margin. */
    if (++pNotch->exeRate >= VOLTAGE_LOOP_EXE_RATE)
    {
        float x;
        float y;

        pNotch->exeRate = 0;

        /* Real pole first: it keeps wideband ADC noise out of the notch, and
           hence out of KP_V, which a notch on its own does nothing about. */
        pNotch->lpfOut += (pfcData->pfcVoltage.vdc - pNotch->lpfOut)
                          * pNotch->lpfCoeff;

        /* Notch, direct form I. */
        x = pNotch->lpfOut;
        y = (pNotch->b0 * x)
          + (pNotch->b1 * pNotch->x1)
          + (pNotch->b2 * pNotch->x2)
          - (pNotch->a1 * pNotch->y1)
          - (pNotch->a2 * pNotch->y2);

        pNotch->x2 = pNotch->x1;
        pNotch->x1 = x;
        pNotch->y2 = pNotch->y1;
        pNotch->y1 = y;
        pNotch->output = y;
    }

    /* Re-published every ISR rather than only on a filter tick, so toggling
       enable at run time takes effect immediately and never leaves the PI
       reading a selection made against the other source. */
    pfcData->vdcFeedback = (pNotch->enable != 0u) ? pNotch->output
                                                  : pfcData->vdcAVG.output;
}
/**
 * <B> Function: PFC_UpdateCurrentFeedback(PFC_T *pfcData) </B>
 * @brief Connect the inductor-current feedback to the control loop, with the
 *        measured offset removed when offset correction is enabled.
 */
inline static void PFC_UpdateCurrentFeedback(PFC_T *pfcData)
{
    /* Always connect the current feedback to the control loop. */
    pfcData->iL = pfcData->pfcCurrent.iL;
#ifdef ENABLE_PFC_CURRENT_OFFSET_CORRECTION
    /* Offset correction is an optional adjustment on top of it. */
    pfcData->iL -= pfcData->pfcCurrent.offset;
#endif
}
/**
 * <B> Function: PFC_SoftStartUpdate(PFC_T *pfcData) </B>
 * @brief Ramp the voltage-loop reference up to nominal at the soft-start rate.
 */
inline static void PFC_SoftStartUpdate(PFC_T *pfcData)
{
    if (pfcData->piVoltage.reference < PFC_OUPUT_VOLTAGE_REFERENCE)
    {
        if(pfcData->rampRate == 0)
        {
            pfcData->piVoltage.reference += RAMP_COUNT;
            pfcData->rampRate = RAMP_RATE;
        }
        else
        {
            pfcData->rampRate--;
        }
    }
    else
    {
        pfcData->piVoltage.reference = PFC_OUPUT_VOLTAGE_REFERENCE;
    }
}
/**
 * <B> Function: PFC_UpdateBoostDutyRatio(PFC_T *pfcData) </B>
 * @brief Compute the ideal boost duty ratio ((Vdc-Vac)/Vdc) from present Vdc,Vac.
 */
inline static void PFC_UpdateBoostDutyRatio(PFC_T *pfcData)
{
    PFC_MEASURE_VOLTAGE_T *pVoltage = &pfcData->pfcVoltage;

    if(pVoltage->vdc > 0)
    {
        /** Boost Duty Ratio = (1 - (Vac/Vdc)) = ((Vdc-Vac)/Vdc) */
        pfcData->boostDutyRatio =
                ((pVoltage->vdc - pfcData->rectifiedVac) / pVoltage->vdc);
    }
}
/**
 * <B> Function: PFC_BurstModeUpdate(PFC_T *pfcData) </B>
 * @brief Burst control at very low load: hold the switch off and freeze the
 *        current integrator below the minimum-power threshold.
 */
inline static void PFC_BurstModeUpdate(PFC_T *pfcData)
{
    /* Test the TOTAL power command, not piVoltage.output. Once the load
       feed-forward carries the load, the voltage-PI output legitimately sits
       near zero AT FULL LOAD, and testing it alone reads that as "no load" and
       switches the converter off under load. SiL 2026-07-27 at loadFF gain 1.0:
       the duty was forced to zero for 22% of the loaded run, in stretches up to
       20 ms, while the feed-forward was asking for 375 W - an 11.4 Hz
       relaxation oscillation with 12 V p-p on the bus. */
    if(pfcData->powerCommand < PFC_MIN_POWER)
    {
        pfcData->duty = 0;
        pfcData->piCurrent.integralOut = 0;
        /* The switch is held off, so the duty that produces the next current
           sample is zero - keep dutyRatio consistent or the conduction-mode
           detector and the DCM factor work off a duty that was never applied. */
        pfcData->dutyRatio = 0;
        pfcData->dutyFF = 0;
    }
}
/**
 * <B> Function: PFC_StateInit(PFC_T *pfcData) </B>
 * @brief PFC_INIT: reset control state, disable PWM, open the inrush relay and
 *        start current-offset measurement. Returns the next state.
 */
static PFC_CTRL_STATE_T PFC_StateInit(PFC_T *pfcData)
{
    PFC_ResetParams(pfcData);
    HAL_PFCPWMDisableOutputs();
    PFC_INRUSH_RELAY = 0;
    PFC_MeasureCurrentInit(&pfcData->pfcCurrent);

    return PFC_PRECHARGE;
}
/**
 * <B> Function: PFC_StatePrecharge(PFC_T *pfcData) </B>
 * @brief PFC_PRECHARGE: wait for the DC bulk capacitor to charge passively
 *        through the diode bridge and the inrush resistor, then bypass the
 *        inrush resistor with the relay. Returns the next state.
 */
static PFC_CTRL_STATE_T PFC_StatePrecharge(PFC_T *pfcData)
{
    /** Timeout, latched: with any standing load on the DC bus the passive
        R-C divider settles BELOW the completion threshold and this state
        would otherwise wait forever - silently, with the short-time-rated
        inrush resistor dissipating the load current. The relay is
        deliberately left OPEN on the way out: closing it into a
        half-charged bus is exactly the surge precharge exists to avoid, and
        if the resistor is a self-protecting PTC the safe end state is
        high-impedance, not bypassed. */
    if (++pfcData->prechargeCount >= PFC_PRECHARGE_TIMEOUT_COUNT)
    {
        pfcData->faultStatus |= PFC_FAULT_PRECHG;
        return PFC_FAULT;
    }

    /** The relay short-circuits the inrush resistor, so the surge it draws is
        set by how far the bus still is from its passive asymptote - the
        rectified input peak less the bridge drops. Referring the completion
        point to that peak instead of to a fixed voltage both minimises the
        surge and keeps precharge working across the declared input range
        (see PFC_PRECHARGE_PEAK_FRACTION).

        vacRMS.sqrOutput is Vrms^2, so the peak is sqrt(2*sqrOutput). Wait for
        the first RMS and AC-offset windows to complete before trusting it:
        until vacAVG converges, offsetVac is still 0 and rectifiedVac - hence
        sqrOutput - is wrong on hardware, where the AC sense sits on a mid-
        scale offset. Both windows close within 20 ms, long before the bus is
        anywhere near the threshold. */
    if((pfcData->vacRMS.status == 1) && (pfcData->vacAVG.status == 1))
    {
        const float peak = sqrtf(2.0f * pfcData->vacRMS.sqrOutput);

        /** vdcAVG.output is the moving average of the measured bus voltage. */
        if(pfcData->vdcAVG.output >= (PFC_PRECHARGE_PEAK_FRACTION * peak))
        {
            PFC_INRUSH_RELAY = 1;
            return PFC_OFFSET_MEAS;
        }
    }
    return PFC_PRECHARGE;
}
/**
 * <B> Function: PFC_StateOffsetMeas(PFC_T *pfcData) </B>
 * @brief PFC_OFFSET_MEAS: accumulate the current-offset average; once the
 *        offset and the AC average are ready, seed the voltage reference and
 *        advance. Returns the next state.
 */
static PFC_CTRL_STATE_T PFC_StateOffsetMeas(PFC_T *pfcData)
{
    PFC_MEASURE_CURRENT_T *pCurrent = &pfcData->pfcCurrent;

    PFC_MeasureCurrentOffset(pCurrent);

    if((pCurrent->status == 1) && (pfcData->vacAVG.status == 1))
    {
        /** On first completion, set the output-voltage reference to the
            measured DC voltage and enable soft start. Seeded from the same
            signal the PI closes on, so the initial error is exactly zero. */
        pfcData->piVoltage.reference = pfcData->vdcFeedback;
        pfcData->pfcVoltage.offsetVac = pfcData->vacAVG.output;
        /** Restart the RMS window: status is sticky once set (nothing clears
            it after a window completes), so without this PFC_WAIT_1CYCLE
            would fall straight through in a single tick instead of waiting.
            Restarting the accumulator mid-window costs no accuracy - vac^2
            has period T/2, so a half-line window yields the exact RMS from
            any starting phase. */
        pfcData->vacRMS.sum = 0;
        pfcData->vacRMS.samples = 0;
        pfcData->vacRMS.status = 0;
        return PFC_WAIT_1CYCLE;
    }
    return PFC_OFFSET_MEAS;
}
/**
 * <B> Function: PFC_StateWait1Cycle(PFC_T *pfcData) </B>
 * @brief PFC_WAIT_1CYCLE: wait for one complete, freshly-started RMS window
 *        (PFC_OFFSET_MEAS restarts it on the way in), then enable PWM and
 *        start closed-loop control. This is a deterministic 10 ms at 50 Hz;
 *        together with the ~16 ms offset-measurement window it also puts
 *        ~26 ms between the inrush-relay close command and the first PWM
 *        pulse, covering typical relay operate + bounce time. Returns the
 *        next state.
 */
static PFC_CTRL_STATE_T PFC_StateWait1Cycle(PFC_T *pfcData)
{
    if(pfcData->vacRMS.status == 1)
    {
        HAL_PFCPWMEnableOutputs();
        return PFC_CTRL_RUN;
    }
    return PFC_WAIT_1CYCLE;
}
/**
 * <B> Function: PFC_StateCtrlRun(PFC_T *pfcData) </B>
 * @brief PFC_CTRL_RUN: the closed-loop control sequence - current feedback,
 *        fault check, soft-start, current-reference generation, boost-duty
 *        estimate, current loop and burst control. Returns the next state.
 */
static PFC_CTRL_STATE_T PFC_StateCtrlRun(PFC_T *pfcData)
{
    PFC_UpdateCurrentFeedback(pfcData);

    PFC_FaultCheck(pfcData);
    if(pfcData->faultStatus != PFC_FAULT_NONE)
    {
        return PFC_FAULT;
    }

    PFC_SoftStartUpdate(pfcData);
    PFC_CurrentRefGenerate(pfcData);
    PFC_UpdateBoostDutyRatio(pfcData);
    PFC_CurrentControlLoop(pfcData);
    PFC_BurstModeUpdate(pfcData);

    return PFC_CTRL_RUN;
}
/**
 * <B> Function: PFC_StateFault(PFC_T *pfcData) </B>
 * @brief PFC_FAULT: hold PWM off and duty at zero; clear each auto-recovering
 *        fault against its hysteresis limit (IP_OC stays latched). When all
 *        faults clear, re-engage and return to PFC_CTRL_RUN. Returns the next
 *        state.
 */
static PFC_CTRL_STATE_T PFC_StateFault(PFC_T *pfcData)
{
    pfcData->duty = 0;
    pfcData->dutyRatio = 0;
    pfcData->dutyFF = 0;
    HAL_PFCPWMDisableOutputs();

    /** Clear input under-voltage once the input recovers above the UV upper
        (recovery) limit - hysteresis vs the UV trip limit. */
    if(pfcData->vacRMS.sqrOutput >= PFC_INPUT_UNDER_VOLTAGE_LIMIT_HI)
    {
        pfcData->faultStatus &= (~PFC_FAULT_IP_UV);
    }
    /** Clear input over-voltage once the input falls below the OV lower
        (recovery) limit - hysteresis vs the OV trip limit. */
    if(pfcData->vacRMS.sqrOutput < PFC_INPUT_OVER_VOLTAGE_LIMIT_LO)
    {
        pfcData->faultStatus &= (~PFC_FAULT_IP_OV);
    }
    /** Clear output over-voltage only once the bus has bled down below the OV
        recovery limit (hysteresis vs the trip limit). */
    if(pfcData->vdcAVG.output < PFC_OUTPUT_OVER_VOLTAGE_RECOVERY_LIMIT)
    {
        pfcData->faultStatus &= (~PFC_FAULT_OP_OV);
    }
    /** Clear output under-voltage once the bus has climbed back above the UV
        recovery limit. With PWM disabled the bus is passively capped at the
        rectified input peak, so this auto-recovers at nominal/high line; at low
        line it holds off until the bus rises - a slow hiccup, since OP_UV
        re-arms only after soft-start reaches nominal again. */
    if(pfcData->vdcAVG.output >= PFC_OUTPUT_UNDER_VOLTAGE_RECOVERY_LIMIT)
    {
        pfcData->faultStatus &= (~PFC_FAULT_OP_UV);
    }
    /** PFC_FAULT_IP_OC and PFC_FAULT_PRECHG are latching: deliberately never
        cleared here, so an over-current event or a precharge timeout holds
        the converter off until a reset (PFC_ServiceInit). */
    if(pfcData->faultStatus == PFC_FAULT_NONE)
    {
        pfcData->piVoltage.integralOut = 0;
        pfcData->piCurrent.integralOut = 0;
        pfcData->piVoltage.reference = pfcData->vdcFeedback;
        HAL_PFCPWMEnableOutputs();
        return PFC_CTRL_RUN;
    }
    return PFC_FAULT;
}
/**
* <B> Function: PFC_ServiceInit()     </B>
* 
* @brief Function calls the PFC_ParamsInit() which initializes the control 
*       parameters.      
* @param none.
* @return none.
* @example
* <CODE> PFC_ServiceInit();        </CODE>
*
*/

void PFC_ServiceInit(void)
{
    /* Make sure ADC does not generate interrupt while initializing parameters*/
	DisablePFCADCInterrupt();
    
    PFC_ParamsInit(&pfcParam);
    
    /* Enable ADC interrupt and begin main loop timing */
    ClearPFCADCIF();
    ClearPFCADCIF_ReadADCBUF();
    EnablePFCADCInterrupt(); 
}
/**
 * <B> Function: PFC_ParamsInit(PFC_T *pfcData)  </B>
 * 
 * @brief Function to initialize PFC related variables 
 * @param Pointer to the data structure containing PFC related variables.
 * PI coefficients, scaling constants etc
 * @return none.
 * @example
 * <code>
 * PFC_ParamsInit(PFC_T *pfcData)
 * </code>
 */
void PFC_ParamsInit(PFC_T *pfcData)
{  
    /** Initialize variables related to RMS calculation - VAC */      
    pfcData->vacRMS.sampleLimit = PFC_RMS_SQUARE_COUNTMAX;
    /** Initialize variables related to Average calculation - VDC */ 
    pfcData->vdcAVG.sampleLimit = PFC_VDC_AVG_SAMPLES;
    
    pfcData->vacAVG.sampleLimit = PFC_INPUT_FREQUENCY_COUNTER;

/** Initialize duty feed-forward. Set before the current-PI limits below,
    which depend on whether it is active. */
    pfcData->dutyFFEnable = PFC_DUTY_FF_ENABLE_DEFAULT;
    pfcData->dutyRatio    = 0;
    pfcData->dutyFF       = 0;
    pfcData->powerCommand = 0;

/** Initialize PI controlling PFC Current Loop. The limits depend on
    dutyFFEnable and are refreshed by the current loop whenever the flag is
    toggled at run time - see PFC_CurrentPILimitsUpdate. */
    pfcData->piCurrent.kp = KP_I;
    pfcData->piCurrent.ki = KI_I;
    PFC_CurrentPILimitsUpdate(pfcData);
    pfcData->dutyFFEnablePrev = pfcData->dutyFFEnable;

/** Initialize PI controlling PFC Voltage Loop */    
    pfcData->piVoltage.kp = KP_V;
    pfcData->piVoltage.ki = KI_V;
    pfcData->piVoltage.maxOutput = PI_V_OUT_MAX;
    pfcData->piVoltage.minOutput = 0;
    
    pfcData->state = PFC_INIT;
    pfcData->faultStatus = PFC_FAULT_NONE;
    /* Average-current reconstruction method, see PFC_DCM_COMP_T. Writable at
     * run time so the methods can be A/B'd on a single build. */
    pfcData->sampleCorrectionEnable = PFC_DCM_COMPENSATION_METHOD;
    pfcData->dcmDetected = 0;
    pfcData->iValleyEst = 0.0f;
    pfcData->sampleCorrFactor = 1.0f;

/** Initialize load-current feed-forward (disabled by default). */
    pfcData->loadFF.scale       = PFC_LOAD_CURRENT_SCALE;
    pfcData->loadFF.filtCoeff   = PFC_LOAD_FF_FILT_COEFF;
    pfcData->loadFF.gain        = PFC_LOAD_FF_GAIN;
    pfcData->loadFF.enable      = PFC_LOAD_FF_ENABLE_DEFAULT;
    pfcData->loadFF.currentFilt = 0;

/** Initialize the Vdc notch + anti-noise pole feeding the voltage PI. The
    coefficients live in the struct rather than being used as literals so they
    can be retuned from X2C-Scope without a rebuild. */
    pfcData->vdcNotch.b0       = PFC_VDC_NOTCH_B0;
    pfcData->vdcNotch.b1       = PFC_VDC_NOTCH_B1;
    pfcData->vdcNotch.b2       = PFC_VDC_NOTCH_B2;
    pfcData->vdcNotch.a1       = PFC_VDC_NOTCH_A1;
    pfcData->vdcNotch.a2       = PFC_VDC_NOTCH_A2;
    pfcData->vdcNotch.lpfCoeff = PFC_VDC_NOTCH_LPF_COEFF;
    pfcData->vdcNotch.enable   = PFC_VDC_NOTCH_ENABLE_DEFAULT;
    PFC_VdcFilterReset(&pfcData->vdcNotch, 0.0f);
    pfcData->vdcFeedback = 0;
}
/**
 * <B> Function: PFC_ResetParams(PFC_T *pData)  </B>
 * 
 * @brief Function to reset the variables related to moving average filter of 
 * Vdc,variables related to moving average filter of Vac,variables related to 
 * PI integrator and the duty cycle.
 * @param Pointer to the data structure containing PFC related variables
 * @return none
 * @example
 * <code>
 * PFC_ResetParams(PFC_T *pData);
 * </code>
 */
void PFC_ResetParams(PFC_T *pData)
{   
    /** Initialize variables related to moving average filter - Vdc */    
    pData->vdcAVG.sum = 0;
    pData->vdcAVG.samples = 0;
    pData->vdcAVG.status = 0;

    /** Initialize variables related to moving average filter - Vac */
    pData->vacAVG.sum = 0;
    pData->vacAVG.samples = 0;
    pData->vacRMS.sum = 0;
    pData->vacRMS.samples = 0;
    pData->vacRMS.status = 0;

    /** Re-settle the Vdc notch on the present measurement, so handing control
        over later does not have to wait for it to charge up from zero. */
    PFC_VdcFilterReset(&pData->vdcNotch, pData->pfcVoltage.vdc);
    pData->vdcFeedback = pData->pfcVoltage.vdc;

    /** Initialize variables related to PI integrator */
    pData->piVoltage.integralOut = 0;
    pData->piCurrent.integralOut = 0;

    /** Initialize the duty cycle */
    pData->duty = 0;
    pData->dutyRatio = 0;
    pData->dutyFF = 0;
    pData->powerCommand = 0;

    /** Restart the precharge timeout dwell. */
    pData->prechargeCount = 0;
}

/**
 * <B> Function: PFC_DcmAverageFactor(PFC_T *pData)  </B>
 *
 * @brief Ratio between the true cycle-average inductor current and the mid-ON
 * sample, i.e. the conduction fraction (d1+d2).
 * @param Pointer to the data structure containing PFC related variables
 * @return correction factor in (0,1]
 * @example
 * <code>
 * factor = PFC_DcmAverageFactor(pData);
 * </code>
 */
static float PFC_DcmAverageFactor(PFC_T *pData)
{
    /* IL is sampled at mid-ON:
     *   CCM: the sample already equals the average IL           -> factor 1.
     *   DCM: the sample is ~Ipk/2, but the cycle-average is LOWER because the
     *        current idles at zero for part of the period:
     *          I_avg = (Ipk/2)*(d1+d2) = sample * (d1 / D_ideal),
     *        with d1 = the ON duty that produced this sample (dutyRatio - NOT
     *        piCurrent.output, which is only the trim once the duty
     *        feed-forward is enabled),
     *        D_ideal = (Vout-Vin)/Vout = boostDutyRatio, and
     *        (d1+d2) = d1/D_ideal < 1 in DCM.
     * Note d2 = d1*Vg/(Vo-Vg) assumes an ideal converter: the diode drop, DCR
     * and Rds_on all stretch the real demagnetising time slightly. */
    float factor = 1.0f;

    if (pData->boostDutyRatio > 0.0f)
    {
        factor = pData->dutyRatio / pData->boostDutyRatio;

        /* Losses/transients can push d1 past D_ideal; that must never inflate
         * the reading, so cap at unity. Under PFC_DCM_COMP_RATIO this cap is
         * also what decides CCM, which is precisely the weakness that
         * PFC_DCM_COMP_VALLEY_EST removes. */
        if (factor > 1.0f)
        {
            factor = 1.0f;
        }
        else if (factor < 0.0f)
        {
            factor = 0.0f;
        }
    }
    return factor;
}
/**
 * <B> Function: PFC_ConductionModeDetect(PFC_T *pData)  </B>
 *
 * @brief Detects CCM/DCM by predicting the inductor current at the end of the
 * OFF time and testing it against zero. Also publishes the estimate itself in
 * pData->iValleyEst for logging.
 * @param Pointer to the data structure containing PFC related variables
 * @return 1 if DCM, 0 if CCM
 * @example
 * <code>
 * pData->dcmDetected = PFC_ConductionModeDetect(pData);
 * </code>
 */
static uint16_t PFC_ConductionModeDetect(PFC_T *pData)
{
    const float d  = pData->dutyRatio;          /* duty that produced this sample */
    const float vg = pData->rectifiedVac;
    const float vo = pData->pfcVoltage.vdc;

    /* Walk the CCM current path forward from the mid-ON sample:
     *    rise over the remaining half of the ON time : +(vg/L)*(d*Ts/2)
     *    fall over the whole OFF time                : +((vg-vo)/L)*(1-d)*Ts
     * Collecting terms,
     *    iValleyEst = i + (Ts/L)*( vg*(1 - d/2) - vo*(1 - d) )
     *
     * In CCM the current really does follow that path, so the estimate is the
     * actual valley and is >= 0. In DCM the current hits zero before the OFF
     * time is up and then sits there, so the continued-slope estimate
     * undershoots into negative territory.
     *
     * The point of doing it this way is the threshold: it is a FIXED zero, not
     * a sampled quantity. Comparing an estimate against a sample (which is what
     * the min(d1/D_ideal,1) clamp effectively does) makes the decision jitter
     * on sample noise right at the boundary, and every toggle is a duty
     * discontinuity that shows up as input current distortion. */
    pData->iValleyEst = pData->iL
                      + (PFC_TS_OVER_L * ((vg * (1.0f - (0.5f * d)))
                                        - (vo * (1.0f - d))));

    return (pData->iValleyEst < 0.0f) ? 1u : 0u;
}
/**
 * <B> Function: PFC_CurrentSampleCorrection(PFC_T *pData)  </B>
 *
 * @brief Function to calculate average value of current in discontinuous
 * conduction mode. Writes averageCurrent, dcmDetected, iValleyEst and
 * sampleCorrFactor.
 * @param Pointer to the data structure containing PFC related variables
 * @return none
 * @example
 * <code>
 * PFC_CurrentSampleCorrection(PFC_T *pData);
 * </code>
 */
static void PFC_CurrentSampleCorrection(PFC_T *pData)
{
    /* Always evaluated, whichever method is driving the loop, so that one run
     * shows what valley estimation would have decided even when it is not the
     * active method. Costs a handful of flops. */
    const uint16_t dcmByValley = PFC_ConductionModeDetect(pData);

    switch (pData->sampleCorrectionEnable)
    {
        case PFC_DCM_COMP_RATIO:
            /* Legacy: the unity cap is the mode decision. Report DCM whenever
             * the cap did not bind, so dcmDetected is directly comparable
             * against the valley method's answer. */
            pData->sampleCorrFactor = PFC_DcmAverageFactor(pData);
            pData->dcmDetected = (pData->sampleCorrFactor < 1.0f) ? 1u : 0u;
            break;

        case PFC_DCM_COMP_VALLEY_EST:
            /* Detect first, then correct only if DCM was actually detected. */
            pData->dcmDetected = dcmByValley;
            pData->sampleCorrFactor = (dcmByValley != 0u)
                                    ? PFC_DcmAverageFactor(pData)
                                    : 1.0f;
            break;

        case PFC_DCM_COMP_OFF:
        default:
            pData->dcmDetected = 0u;
            pData->sampleCorrFactor = 1.0f;
            break;
    }

    pData->averageCurrent = pData->iL * pData->sampleCorrFactor;
}
/**
 * <B> Function: PFC_DutyFeedForward(PFC_T *pData)  </B>
 *
 * @brief Open-loop duty that delivers currentReference at the present
 * operating point, so the current PI only has to trim losses instead of
 * synthesising the whole (Vo-Vg)/Vo profile through its integrator.
 * @param Pointer to the data structure containing PFC related variables
 * @return feed-forward duty ratio in [0, PFC_MAX_DUTY]
 * @example
 * <code>
 * pData->dutyFF = PFC_DutyFeedForward(pData);
 * </code>
 */
static float PFC_DutyFeedForward(PFC_T *pData)
{
    /* CCM: the inductor volt-second balance fixes the duty independently of
     * the current, so the ideal boost ratio IS the feed-forward. */
    float ff = pData->boostDutyRatio;

    /* DCM: volt-second balance no longer pins the duty - the average current
     * is a static function of it,
     *      I_avg = (Ts*Vg*d^2) / (2L*D_ideal)
     * so the duty that open-loop delivers the reference is
     *      d = sqrt( (2L/Ts) * Iref * D_ideal / Vg ).
     * Substituting d = D_ideal shows the two branches meet exactly at the
     * CCM/DCM boundary, so switching between them introduces no step.
     * dcmDetected comes from PFC_CurrentSampleCorrection, which has already
     * run this cycle. */
    if (pData->dcmDetected != 0u)
    {
        /* Vg is floored, not tested: falling back to the CCM branch here would
         * be badly wrong, because at the zero crossing D_ideal -> 1 while the
         * demanded current is ~0 - that would command near-maximum duty into
         * the notch. Flooring instead keeps the expression finite and, since
         * currentReference is proportional to Vg, tapers ff smoothly to zero
         * as Vg does. Above the floor the result is exact. */
        float vg = pData->rectifiedVac;
        float arg;

        if (vg < PFC_DUTY_FF_VG_MIN)
        {
            vg = PFC_DUTY_FF_VG_MIN;
        }
        /* boostDutyRatio goes negative if Vg ever exceeds Vdc (sag, precharge),
         * which would make the argument negative. */
        arg = (PFC_TWO_L_OVER_TS * pData->currentReference
               * pData->boostDutyRatio) / vg;
        ff = (arg > 0.0f) ? sqrtf(arg) : 0.0f;
    }

    /* D_ideal exceeds PFC_MAX_DUTY either side of the zero crossing; the
     * converter simply cannot follow there, so cap rather than command a duty
     * the PWM will clip anyway. */
    if (ff > PFC_MAX_DUTY)
    {
        ff = PFC_MAX_DUTY;
    }
    else if (ff < 0.0f)
    {
        ff = 0.0f;
    }
    return ff;
}
/**
 * <B> Function: PFC_CurrentPILimitsUpdate(PFC_T *pData)  </B>
 *
 * @brief Set the current-PI output limits to match the ACTIVE duty
 * feed-forward mode. With the feed-forward on, the PI is a trim and the tight
 * symmetric bound doubles as its anti-windup; with it off (legacy) the PI
 * supplies the whole duty. Called from PFC_ParamsInit and again from
 * PFC_CurrentControlLoop whenever dutyFFEnable is toggled at run time -
 * setting the limits only at init left a run-time 1->0 toggle clamped at
 * +/-PFC_DUTY_TRIM_MAX, unable to reach the ~0.15..0.95 duty the boost needs.
 * @param Pointer to the data structure containing PFC related variables
 * @return none
 */
static void PFC_CurrentPILimitsUpdate(PFC_T *pData)
{
    if (pData->dutyFFEnable != 0u)
    {
        /* The PI is a trim on top of the feed-forward, so it must be able to
           go negative, and a tight symmetric bound is the anti-windup. */
        pData->piCurrent.maxOutput =  PFC_DUTY_TRIM_MAX;
        pData->piCurrent.minOutput = -PFC_DUTY_TRIM_MAX;
    }
    else
    {
        /* Legacy: the PI supplies the whole duty. */
        pData->piCurrent.maxOutput = PFC_MAX_DUTY;
        pData->piCurrent.minOutput = 0;
    }
}
/**
 * <B> Function: PFC_CurrentControlLoop(PFC_T *pData)  </B>
 *
 * @brief Function to execute current control loop of PFC
 * @param Pointer to the data structure containing PFC related variables
 * @return none
 * @example
 * <code>
 * PFC_CurrentControlLoop(PFC_T *pData);
 * </code>
 */
inline static void PFC_CurrentControlLoop(PFC_T *pData)
{
    float dutyRatio;
    float duty;

    /** Ensure PFC current  is not negative.*/
    if (pData->iL < 0)
    {
        pData->iL  = PFC_IL_MIN;
    }
    /** Calculate average current if converter operates in discontinuous
        conduction mode. In continuous conduction mode, measured current is
        used as is ,as average current is obtained. The method is selected by
        pData->sampleCorrectionEnable (PFC_DCM_COMP_T).
        NOTE: this consumes pData->dutyRatio, which still holds the duty that
        produced the present sample - it is only updated at the end of this
        function. */
    PFC_CurrentSampleCorrection(pData);

    /** dutyFFEnable is documented as run-time writable (X2C A/B testing).
        Detect a toggle, refresh the PI limits to match the new mode, and hand
        the operating point between the integrator and the feed-forward so the
        switch is approximately bumpless. The handover terms are estimates
        (last cycle's dutyFF, this cycle's boostDutyRatio - the DCM branch is
        lower); the trim clamp and the back-calculation below absorb the
        residual within a few cycles. */
    if (pData->dutyFFEnable != pData->dutyFFEnablePrev)
    {
        PFC_CurrentPILimitsUpdate(pData);
        if (pData->dutyFFEnable != 0u)
        {
            /* FF takes over ~D_ideal of the duty; remove it from the PI. */
            pData->piCurrent.integralOut -= pData->boostDutyRatio;
        }
        else
        {
            /* The PI must now supply what the FF was delivering. */
            pData->piCurrent.integralOut += pData->dutyFF;
        }
        pData->dutyFFEnablePrev = pData->dutyFFEnable;
    }

    /* Populate the reference/input fields for logging. The PI update only
     * consumes .error, so these are purely for a self-describing bus. */
    pData->piCurrent.reference = pData->currentReference;
    pData->piCurrent.input     = pData->averageCurrent;
    pData->piCurrent.error = (pData->currentReference - pData->averageCurrent);

    PFC_ControllerPIUpdate(&pData->piCurrent);

    /** Total duty = feed-forward + PI trim. With the feed-forward enabled the
        PI output is a small correction bounded by +/-PFC_DUTY_TRIM_MAX; with
        it disabled dutyFF is zero and the PI spans 0..PFC_MAX_DUTY as before
        (the limits are set to match in PFC_ParamsInit). */
    pData->dutyFF = (pData->dutyFFEnable != 0u) ? PFC_DutyFeedForward(pData)
                                                : 0.0f;
    dutyRatio = pData->dutyFF + pData->piCurrent.output;

    /** Clamp the SUM, and give the integrator back exactly what the clamp
        removed (back-calculation anti-windup). The previous code slammed
        integralOut to PI_I_OUT_MAX on saturation, which is wrong once the PI
        output is a trim - and even without the feed-forward it discarded the
        integrator state instead of holding it. */
    if (dutyRatio > PFC_MAX_DUTY)
    {
        pData->piCurrent.integralOut -= (dutyRatio - PFC_MAX_DUTY);
        dutyRatio = PFC_MAX_DUTY;
    }
    else if (dutyRatio < PFC_MIN_DUTY)
    {
        pData->piCurrent.integralOut += (PFC_MIN_DUTY - dutyRatio);
        dutyRatio = PFC_MIN_DUTY;
    }
    pData->dutyRatio = dutyRatio;

    /** Calculate duty cycle of PWM that controls PFC in terms of PWM Period */
    duty  = (dutyRatio * PFC_LOOPTIME_TCY);
    if (duty  > PFC_MAX_DUTY_COUNTS)
    {
        pData->duty = PFC_MAX_DUTY_COUNTS;
    }
    else if (duty  < PFC_MIN_DUTY_COUNTS)
    {
        pData->duty = PFC_MIN_DUTY_COUNTS;
    }
    else
    {
        pData->duty = duty;
    }
}
/**
 * <B> Function: PFC_CurrentRefGenerate(PFC_T *pData)  </B>
 * 
 * @brief Function to calculate current reference for the current control loop
 * @param Pointer to the data structure containing PFC related variables
 * @return none
 * @example
 * <code>
 * PFC_CurrentRefGenerate(PFC_T *pData);
 * </code>
 */
inline static void PFC_CurrentRefGenerate(PFC_T *pData)
{ 
    /** PI Execution - PFC output voltage control.
        Voltage PI is called at the rate specified by VOLTAGE_LOOP_EXE_RATE */
    if (++pData->voltLoopExeRate >= VOLTAGE_LOOP_EXE_RATE)
    {
        pData->piVoltage.error = pData->piVoltage.reference-pData->vdcFeedback;

        /* Gain-schedule the integral term with hysteresis: halve Ki for large
           errors, restore full Ki for small errors, and hold the current Ki
           inside the [LO, HI] band so it cannot dither at the switch point.
           piVoltage.ki persists across ticks, so no extra state is needed. */
        if((pData->piVoltage.error > PFC_VOLTAGE_ERR_GAIN_HI) ||
           (pData->piVoltage.error < -PFC_VOLTAGE_ERR_GAIN_HI))
        {
            pData->piVoltage.ki = KI_V / 2;
        }
        else if((pData->piVoltage.error < PFC_VOLTAGE_ERR_GAIN_LO) &&
                (pData->piVoltage.error > -PFC_VOLTAGE_ERR_GAIN_LO))
        {
            pData->piVoltage.ki = KI_V;
        }
        /* else: within the hysteresis band - hold the previous Ki. */
        /* Record the measurement for a self-describing bus; the reference is
         * already set by the soft-start ramp. */
        pData->piVoltage.input = pData->vdcFeedback;
        PFC_ControllerPIUpdate(&pData->piVoltage);
        pData->voltLoopExeRate = 0;
    }
    
    /** Current reference = powerCommand * rectifiedVac * KMUL / VacRMS^2.
        powerCommand is the voltage-loop output plus, when enabled, the load-
        power feed-forward (loadFF.powerFF). The feed-forward supplies the load
        power directly so the slow voltage loop only trims losses/errors; this
        cancels the load disturbance in the DC-bus power balance and sharply
        improves the load-step response. */
    {
        float powerCommand = pData->piVoltage.output;
        if (pData->loadFF.enable)
        {
            powerCommand += pData->loadFF.powerFF;
        }
        /* Published so burst control tests the real command - see
           PFC_BurstModeUpdate. */
        pData->powerCommand = powerCommand;
        pData->currentReference = (float)((powerCommand * pData->rectifiedVac * KMUL)
                            / pData->vacRMS.sqrOutput);
    }
    /**  Perform Boundary check of generated current reference */
    if (pData->currentReference > PFC_IREF_PEAK_MAX)
    {
        pData->currentReference = PFC_IREF_PEAK_MAX;
    }
    else if (pData->currentReference < 0)
    {
        pData->currentReference = 0;
    }
}
/**
 * <B> Function: float PFC_SignalRectification(PFC_MEASURE_VOLTAGE_T *pSignal)  </B>
 * 
 * @brief Function to rectify the input AC voltage
 * @param Pointer to the data structure containing measured voltage
 * @return Rectified signal
 * @example
 * <code>
 * PFC_SignalRectification();
 * </code>
 */
float PFC_SignalRectification(PFC_MEASURE_VOLTAGE_T *pSignal)
{   
    float output = pSignal->vac - pSignal->offsetVac;
    
    if(output < 0)
    {
        output = -(output);
    }  
    return(output);
}
/**
 * <B> Function: PFC_SquaredRMSCalculate(PFC_RMS_SQUARE_T *pData,float input)  </B>
 * 
 * @brief Function to calculate RMS value of an input signal
 * @param Pointer to the data structure containing variables related to RMS 
 * calculation, current value of signal  
 * @return none.
 * @example
 * <code>
 * PFC_SquaredRMSCalculate(PFC_RMS_SQUARE_T *pData,float input);
 * </code>
 */
static void PFC_SquaredRMSCalculate(PFC_RMS_SQUARE_T *pData,float input)
{       
        pData->sum += (float) (input*input);
    pData->samples++;
    /** Match PFC_Average's ordering: accumulate, increment, then test with >=
        so each window integrates exactly sampleLimit terms and divides by the
        same count. (Previously the sum held sampleLimit+1 terms but divided by
        sampleLimit, biasing sqrOutput high by 1/sampleLimit and stretching the
        window one sample past the half-line cycle.) */
    if(pData->samples >= pData->sampleLimit)
    {
       pData->sqrOutput = (float)((pData->sum/pData->sampleLimit));
       pData->status    = 1;
       pData->samples   = 0;
       pData->sum       = 0;
    }
}
/**
 * <B> Function: PFC_Average(PFC_AVG_T *pData,float input)  </B>
 * 
 * @brief Function to calculate moving average value of an input Signal
 * @param Pointer to the data structure containing variables related to average 
 * calculation, current value of signal 
 * @return none.
 * @example
 * <code>
 * PFC_Average(PFC_AVG_T *pData,float input);
 * </code>
 */
static void PFC_Average(PFC_AVG_T *pData,float input)
{
    pData->sum = pData->sum + input;
    pData->samples++;
    if(pData->samples >= pData->sampleLimit) 
    {
        pData->output  = (float)(pData->sum/pData->sampleLimit);
        pData->status  = 1;
        pData->sum     = 0;
        pData->samples = 0; 
    }
}


/**
 * <B> Function: PFC_FaultCheck(PFC_T *pData)  </B>
 * 
 * @brief Function to check the different fault status
 * @param Pointer to the data structure containing PFC related variables
 * @return none
 * @example
 * <code>
 * PFC_FaultCheck(PFC_T *pData);
 * </code>
 */
void PFC_FaultCheck(PFC_T *pData)
{
    /** Recompute the fault mask from scratch each pass so faults never
        accumulate or alias; each fault is an independent bit set with |=.
        Latching / recovery is handled by the PFC_FAULT state, not here. */
    uint16_t faults = PFC_FAULT_NONE;

    /*Check the condition for output over voltage*/
    if(pData->vdcAVG.output >= PFC_OUTPUT_OVER_VOLTAGE_LIMIT)
    {
        faults |= PFC_FAULT_OP_OV;
    }
    /*Check the condition for input under voltage*/
    if(pData->vacRMS.sqrOutput < PFC_INPUT_UNDER_VOLTAGE_LIMIT_LO)
    {
        faults |= PFC_FAULT_IP_UV;
    }
    /*Check the condition for input over voltage*/
    if(pData->vacRMS.sqrOutput >= PFC_INPUT_OVER_VOLTAGE_LIMIT_HI)
    {
        faults |= PFC_FAULT_IP_OV;
    }
    /** Instantaneous input over-current - software OCP on the offset-corrected
        inductor current (symmetric test catches either polarity). Latching:
        PFC_FAULT provides no auto-clear, because once PWM is disabled the
        inductor current decays to zero in microseconds and a threshold-based
        clear would self-clear immediately. */
    if((pData->iL >=  PFC_INPUT_OVER_CURRENT_PEAK) ||
       (pData->iL <= -PFC_INPUT_OVER_CURRENT_PEAK))
    {
        faults |= PFC_FAULT_IP_OC;
    }
    /** Output under-voltage (bus collapse / boost failure / overload), armed
        only once soft-start has reached the nominal reference - during the
        ramp the bus is legitimately below nominal. Auto-recovering with
        hysteresis (see the UV recovery clear in PFC_FAULT). */
    if((pData->piVoltage.reference >= PFC_OUPUT_VOLTAGE_REFERENCE) &&
       (pData->vdcAVG.output < PFC_OUTPUT_UNDER_VOLTAGE_LIMIT))
    {
        faults |= PFC_FAULT_OP_UV;
    }

    pData->faultStatus = faults;
}
// </editor-fold>