// <editor-fold defaultstate="collapsed" desc="Description/Instruction ">
/**
 * @file pfc.c
 *
 * @brief This module has functions required for Power Factor Correction Control
 */
// </editor-fold>

// <editor-fold defaultstate="collapsed" desc="Disclaimer ">

/*******************************************************************************
* SOFTWARE LICENSE AGREEMENT
* 
* � [2024] Microchip Technology Inc. and its subsidiaries
* 
* Subject to your compliance with these terms, you may use this Microchip 
* software and any derivatives exclusively with Microchip products. 
* You are responsible for complying with third party license terms applicable to
* your use of third party software (including open source software) that may 
* accompany this Microchip software.
* 
* Redistribution of this Microchip software in source or binary form is allowed 
* and must include the above terms of use and the following disclaimer with the
* distribution and accompanying materials.
* 
* SOFTWARE IS "AS IS." NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY,
* APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,
* MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT WILL 
* MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR 
* CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND WHATSOEVER RELATED TO
* THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS BEEN ADVISED OF THE 
* POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY
* LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL
* NOT EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR THIS
* SOFTWARE
*
* You agree that you are solely responsible for testing the code and
* determining its suitability.  Microchip has no obligation to modify, test,
* certify, or support the code.
*
*******************************************************************************/
// </editor-fold>

// <editor-fold defaultstate="collapsed" desc="HEADER FILES ">
    
#ifdef __XC16__  // See comments at the top of this header file
    #include <xc.h>
#endif // __XC16__

#include <stdint.h>
#include <stdbool.h>
#include "libq.h"
#include "pfc.h"
#include "board_service.h"
#include "diagnostics.h"

// </editor-fold> 

// <editor-fold defaultstate="collapsed" desc="Function Declarations ">

static float PFC_SignalRectification(PFC_MEASURE_VOLTAGE_T *);
static float PFC_DcmAverageFactor(PFC_T *);
static uint16_t PFC_ConductionModeDetect(PFC_T *);
static void PFC_CurrentSampleCorrection(PFC_T *);
static void PFC_Average(PFC_AVG_T *,float);
static void PFC_SquaredRMSCalculate(PFC_RMS_SQUARE_T *,float);

inline static void PFC_CurrentRefGenerate(PFC_T *);
inline static void PFC_CurrentControlLoop(PFC_T *);

static void PFC_ParamsInit(PFC_T *);
static void PFC_ResetParams(PFC_T *);
static void PFC_FaultCheck(PFC_T *);
void PFC_StateMachine(PFC_T *);

// </editor-fold> 

// <editor-fold defaultstate="collapsed" desc="Global Variables  ">

PFC_T pfcParam;
uint16_t counter = 0;

// </editor-fold>

// <editor-fold defaultstate="collapsed" desc="INTERFACE FUNCTIONS ">
/**
* <B> Function: PFC_ADCInterrupt()  </B>
*
* @brief ADC interrupt vector ,and it performs following actions:
*        (1) Reads DC BUS voltage,input AC voltage and inductor current feedback 
*            from ADC data buffers.
*        (2) Executes Power Factor Correction State machine
*        (3) Loads duty cycle value generated by PFC current control loop to 
*            PWM Duty Register
*        (4) Executes the DiagnosticsStepIsr() for Data visualization 
*            through X2C Scope
*/
void __attribute__((__interrupt__,no_auto_psv)) PFC_ADCInterrupt()
{    
    /** Load ADC Buffer data to respective variables */
    pfcParam.pfcVoltage.outputVoltage       = ADCBUF_VDC>>1;
    pfcParam.pfcVoltage.acVoltage           = ADCBUF_PFC_VAC;
    pfcParam.pfcCurrent.inductorCurrent     = ADCBUF_PFC_IL;
    pfcParam.pfcCurrent2.inductorCurrent     = ADCBUF_PFC_IL2;
    
    pfcParam.pfcVoltage.vdc  = (float)(pfcParam.pfcVoltage.outputVoltage*ADC_VOLTAGE_SCALE);
    pfcParam.pfcVoltage.vac  = (float)(pfcParam.pfcVoltage.acVoltage*ADC_VOLTAGE_SCALE);
    pfcParam.pfcCurrent.iL   = (float)(pfcParam.pfcCurrent.inductorCurrent*ADC_CURRENT_SCALE);
    pfcParam.pfcCurrent2.iL   = (float)(pfcParam.pfcCurrent2.inductorCurrent*ADC_CURRENT_SCALE);
    
    
    PFC_StateMachine(&pfcParam);

#ifdef DEBUG_BOOST
    PFC_ENABLE_SIGNAL = 1;
    pfcParam.duty  = DEBUG_PFC_DUTY;
#endif
    
    PFC_PWM_PDC = pfcParam.duty;  
    #ifdef ENABLE_DIAGNOSTICS
    if (counter < 3)
    {
        counter++;
    }
    else
    {
        DiagnosticsStepIsr();
        counter = 0;
    }
    #endif

    ClearPFCADCIF();
}
/**
 * <B> Function: PFC_StateMachine(PFC_T *pfcData)  </B>
 * @brief Function to perform  - VAC RMS calculation, calculate moving average 
 *        of Vdc, PFC voltage control loop,  generate current reference, PFC  
 *        current control loop.
 * @param none.
 * @return none.
 * @example
 * <code>
 * status = PFC_StateMachine();
 * </code>
 */
void PFC_StateMachine(PFC_T *pfcData)
{    
    uint16_t pfcState = pfcData->state;
    PFC_MEASURE_CURRENT_T *pCurrent = &pfcData->pfcCurrent;
    PFC_MEASURE_CURRENT_T *pCurrent2 = &pfcData->pfcCurrent2;
    PFC_MEASURE_VOLTAGE_T *pVoltage = &pfcData->pfcVoltage;
    
    /** Calculate average of PFC output voltage (DC voltage) feedback 
    to remove line frequency ripple */
    PFC_Average(&pfcData->vdcAVG,pVoltage->vdc);
    pfcData->outputVdc = pfcData->vdcAVG.output;
    /** Calculate average of input AC voltage feedback for offset correction */
    PFC_Average(&pfcData->vacAVG,pVoltage->vac);
    pVoltage->offsetVac = pfcData->vacAVG.output;

    /** Function to rectify the input AC voltage */
    pfcData->rectifiedVac = PFC_SignalRectification(pVoltage);
    
    /** Calculate RMS Square of rectified input voltage  */
    PFC_SquaredRMSCalculate(&pfcData->vacRMS,pfcData->rectifiedVac);
    
    switch(pfcState)
    {
        case PFC_INIT:

            PFC_ResetParams(pfcData);
            HAL_PFCPWMDisableOutputs();
            PFC_INRUSH_RELAY = 0;
            PFC_MeasureCurrentInit(pCurrent);

            pfcState = PFC_PRECHARGE;

        break;
        case PFC_PRECHARGE:
            /** Wait for the DC bulk capacitor to charge passively through the
                diode bridge and the inrush resistor. vdcAVG.output is the
                moving-average of the measured bus voltage in volts. */
            if(pfcData->vdcAVG.output >= PFC_PRECHARGE_THRESHOLD)
            {
                PFC_INRUSH_RELAY = 1;
                pfcState = PFC_OFFSET_MEAS;
            }
        break;
        case PFC_OFFSET_MEAS:
            PFC_MeasureCurrentOffset(pCurrent);
            
            if(pCurrent->status == 1)
            {
                if(pfcData->vacAVG.status == 1)
                {
                    /** Upon first entry into this loop, set PFC output voltage 
                        reference as measures DC voltage and enable  soft start */
                    pfcData->piVoltage.reference = pfcData->vdcAVG.output;
                    pVoltage->offsetVac = pfcData->vacAVG.output;
                    pfcState = PFC_WAIT_1CYCLE;
                }
            }
        break;
        case PFC_WAIT_1CYCLE:

            if(pfcData->vacRMS.status == 1)
            {  
                HAL_PFCPWMEnableOutputs();
                pfcState = PFC_CTRL_RUN;
            }
            
        break;
        case PFC_CTRL_RUN:
            
            /* Always connect the current feedback to the control loop. */
            pfcData->iL = pCurrent->iL;
#ifdef ENABLE_PFC_CURRENT_OFFSET_CORRECTION
            /* Offset correction is an optional adjustment on top of it. */
            pfcData->iL -= pCurrent->offset;
#endif
            
            PFC_FaultCheck(pfcData);

            if(pfcData->faultStatus == PFC_FAULT_NONE)
            {
                /** Perform soft start when enabled */
                if (pfcData->piVoltage.reference < PFC_OUPUT_VOLTAGE_REFERENCE)
                {
                    if(pfcData->rampRate == 0)
                    {
                        pfcData->piVoltage.reference = pfcData->piVoltage.reference + RAMP_COUNT;
                        pfcData->rampRate = RAMP_RATE;
                    }
                    else
                    {
                        pfcData->rampRate--;
                    }
                }
                else
                {
                    pfcData->piVoltage.reference = PFC_OUPUT_VOLTAGE_REFERENCE; 
                }

                PFC_CurrentRefGenerate(pfcData);                

                if(pVoltage->vdc > 0)
                {
                    /** Calculate the ideal value of boost converter duty ratio 
                        based on current value of Vdc and Vac. 
                        Boost Duty Ratio = (1 - (Vac/Vdc))
                                         = ((Vdc-Vac)/Vdc) */
                    pfcData->boostDutyRatio = ((pVoltage->vdc - 
                                pfcData->rectifiedVac)/pVoltage->vdc) ;
                }

                PFC_CurrentControlLoop(pfcData);
                
                if(pfcData->piVoltage.output < PFC_MIN_POWER)
                {
                    pfcData->duty = 0;
                    pfcData->piCurrent.integralOut = 0;
                }
            }
            else
            {
                pfcState = PFC_FAULT; 
            }
            break;
        case PFC_FAULT:
            pfcData->duty = 0;
            HAL_PFCPWMDisableOutputs();
            
            if(pfcData->vacRMS.sqrOutput >= PFC_INPUT_UNDER_VOLTAGE_LIMIT_HI)
            {
                pfcData->faultStatus &= (~PFC_FAULT_IP_UV);    
            }
            if(pfcData->vacRMS.sqrOutput < PFC_INPUT_OVER_VOLTAGE_LIMIT_LO )
            {
                pfcData->faultStatus &= (~PFC_FAULT_IP_OV);
            }
            if(pfcData->faultStatus == PFC_FAULT_NONE)
            {
                pfcData->piVoltage.integralOut = 0;
                pfcData->piCurrent.integralOut = 0;
                pfcData->piVoltage.reference = pfcData->vdcAVG.output;
                pfcState = PFC_CTRL_RUN;
                HAL_PFCPWMEnableOutputs();
            }
        break;
        default:
        break;   
    }
    pfcData->state = pfcState;
}
/**
* <B> Function: PFC_ServiceInit()     </B>
* 
* @brief Function calls the PFC_ParamsInit() which initializes the control 
*       parameters.      
* @param none.
* @return none.
* @example
* <CODE> PFC_ServiceInit();        </CODE>
*
*/

void PFC_ServiceInit(void)
{
    /* Make sure ADC does not generate interrupt while initializing parameters*/
	DisablePFCADCInterrupt();
    
    PFC_ParamsInit(&pfcParam);
    
    /* Enable ADC interrupt and begin main loop timing */
    ClearPFCADCIF();
    ClearPFCADCIF_ReadADCBUF();
    EnablePFCADCInterrupt(); 
}
/**
 * <B> Function: PFC_ParamsInit(PFC_T *pfcData)  </B>
 * 
 * @brief Function to initialize PFC related variables 
 * @param Pointer to the data structure containing PFC related variables.
 * PI coefficients, scaling constants etc
 * @return none.
 * @example
 * <code>
 * PFC_ParamsInit(PFC_T *pfcData)
 * </code>
 */
void PFC_ParamsInit(PFC_T *pfcData)
{  
    /** Initialize variables related to RMS calculation - VAC */      
    pfcData->vacRMS.sampleLimit = PFC_RMS_SQUARE_COUNTMAX;
    /** Initialize variables related to Average calculation - VDC */ 
    pfcData->vdcAVG.scaler = PFC_AVG_SCALER;
    pfcData->vdcAVG.sampleLimit = 1<<pfcData->vdcAVG.scaler;
    
    pfcData->vacAVG.sampleLimit = PFC_INPUT_FREQUENCY_COUNTER;

/** Initialize PI controlling PFC Current Loop */    
    pfcData->piCurrent.kp = KP_I;
    pfcData->piCurrent.ki = KI_I;
//    pfcData->piCurrent.kpScale = KP_I_SCALE;
//    pfcData->piCurrent.kiScale = KI_I_SCALE;
    pfcData->piCurrent.maxOutput = PFC_MAX_DUTY;
    pfcData->piCurrent.minOutput = 0;
    
/** Initialize PI controlling PFC Voltage Loop */    
    pfcData->piVoltage.kp = KP_V;
    pfcData->piVoltage.ki = KI_V;
    pfcData->piVoltage.maxOutput = PI_V_OUT_MAX;
    pfcData->piVoltage.minOutput = 0;
    
    pfcData->state = PFC_INIT;
    pfcData->faultStatus = PFC_FAULT_NONE;
    /* Average-current reconstruction method, see PFC_DCM_COMP_T. Writable at
     * run time so the methods can be A/B'd on a single build. */
    pfcData->sampleCorrectionEnable = PFC_DCM_COMPENSATION_METHOD;
    pfcData->dcmDetected = 0;
    pfcData->iValleyEst = 0.0f;
    pfcData->sampleCorrFactor = 1.0f;
}
/**
 * <B> Function: PFC_ResetParams(PFC_T *pData)  </B>
 * 
 * @brief Function to reset the variables related to moving average filter of 
 * Vdc,variables related to moving average filter of Vac,variables related to 
 * PI integrator and the duty cycle.
 * @param Pointer to the data structure containing PFC related variables
 * @return none
 * @example
 * <code>
 * PFC_ResetParams(PFC_T *pData);
 * </code>
 */
void PFC_ResetParams(PFC_T *pData)
{   
    /** Initialize variables related to moving average filter - Vdc */    
    pData->vdcAVG.sum = 0;
    pData->vdcAVG.samples = 0;
    pData->vdcAVG.status = 0;

    /** Initialize variables related to moving average filter - Vac */
    pData->vacAVG.sum = 0;
    pData->vacAVG.samples = 0;
    pData->vacRMS.sum = 0;
    pData->vacRMS.samples = 0;
    pData->vacRMS.peak = 0;
    pData->vacRMS.status = 0;

    /** Initialize variables related to PI integrator */
    pData->piVoltage.integralOut = 0;
    pData->piCurrent.integralOut = 0;

    /** Initialize the duty cycle */
    pData->duty = 0;
}

/**
 * <B> Function: PFC_DcmAverageFactor(PFC_T *pData)  </B>
 *
 * @brief Ratio between the true cycle-average inductor current and the mid-ON
 * sample, i.e. the conduction fraction (d1+d2).
 * @param Pointer to the data structure containing PFC related variables
 * @return correction factor in (0,1]
 * @example
 * <code>
 * factor = PFC_DcmAverageFactor(pData);
 * </code>
 */
static float PFC_DcmAverageFactor(PFC_T *pData)
{
    /* IL is sampled at mid-ON:
     *   CCM: the sample already equals the average IL           -> factor 1.
     *   DCM: the sample is ~Ipk/2, but the cycle-average is LOWER because the
     *        current idles at zero for part of the period:
     *          I_avg = (Ipk/2)*(d1+d2) = sample * (d1 / D_ideal),
     *        with d1 = ON duty (piCurrent.output),
     *        D_ideal = (Vout-Vin)/Vout = boostDutyRatio, and
     *        (d1+d2) = d1/D_ideal < 1 in DCM.
     * Note d2 = d1*Vg/(Vo-Vg) assumes an ideal converter: the diode drop, DCR
     * and Rds_on all stretch the real demagnetising time slightly. */
    float factor = 1.0f;

    if (pData->boostDutyRatio > 0.0f)
    {
        factor = pData->piCurrent.output / pData->boostDutyRatio;

        /* Losses/transients can push d1 past D_ideal; that must never inflate
         * the reading, so cap at unity. Under PFC_DCM_COMP_RATIO this cap is
         * also what decides CCM, which is precisely the weakness that
         * PFC_DCM_COMP_VALLEY_EST removes. */
        if (factor > 1.0f)
        {
            factor = 1.0f;
        }
        else if (factor < 0.0f)
        {
            factor = 0.0f;
        }
    }
    return factor;
}
/**
 * <B> Function: PFC_ConductionModeDetect(PFC_T *pData)  </B>
 *
 * @brief Detects CCM/DCM by predicting the inductor current at the end of the
 * OFF time and testing it against zero. Also publishes the estimate itself in
 * pData->iValleyEst for logging.
 * @param Pointer to the data structure containing PFC related variables
 * @return 1 if DCM, 0 if CCM
 * @example
 * <code>
 * pData->dcmDetected = PFC_ConductionModeDetect(pData);
 * </code>
 */
static uint16_t PFC_ConductionModeDetect(PFC_T *pData)
{
    const float d  = pData->piCurrent.output;   /* duty that produced this sample */
    const float vg = pData->rectifiedVac;
    const float vo = pData->pfcVoltage.vdc;

    /* Walk the CCM current path forward from the mid-ON sample:
     *    rise over the remaining half of the ON time : +(vg/L)*(d*Ts/2)
     *    fall over the whole OFF time                : +((vg-vo)/L)*(1-d)*Ts
     * Collecting terms,
     *    iValleyEst = i + (Ts/L)*( vg*(1 - d/2) - vo*(1 - d) )
     *
     * In CCM the current really does follow that path, so the estimate is the
     * actual valley and is >= 0. In DCM the current hits zero before the OFF
     * time is up and then sits there, so the continued-slope estimate
     * undershoots into negative territory.
     *
     * The point of doing it this way is the threshold: it is a FIXED zero, not
     * a sampled quantity. Comparing an estimate against a sample (which is what
     * the min(d1/D_ideal,1) clamp effectively does) makes the decision jitter
     * on sample noise right at the boundary, and every toggle is a duty
     * discontinuity that shows up as input current distortion. */
    pData->iValleyEst = pData->iL
                      + (PFC_TS_OVER_L * ((vg * (1.0f - (0.5f * d)))
                                        - (vo * (1.0f - d))));

    return (pData->iValleyEst < 0.0f) ? 1u : 0u;
}
/**
 * <B> Function: PFC_CurrentSampleCorrection(PFC_T *pData)  </B>
 *
 * @brief Function to calculate average value of current in discontinuous
 * conduction mode. Writes averageCurrent, dcmDetected, iValleyEst and
 * sampleCorrFactor.
 * @param Pointer to the data structure containing PFC related variables
 * @return none
 * @example
 * <code>
 * PFC_CurrentSampleCorrection(PFC_T *pData);
 * </code>
 */
static void PFC_CurrentSampleCorrection(PFC_T *pData)
{
    /* Always evaluated, whichever method is driving the loop, so that one run
     * shows what valley estimation would have decided even when it is not the
     * active method. Costs a handful of flops. */
    const uint16_t dcmByValley = PFC_ConductionModeDetect(pData);

    switch (pData->sampleCorrectionEnable)
    {
        case PFC_DCM_COMP_RATIO:
            /* Legacy: the unity cap is the mode decision. Report DCM whenever
             * the cap did not bind, so dcmDetected is directly comparable
             * against the valley method's answer. */
            pData->sampleCorrFactor = PFC_DcmAverageFactor(pData);
            pData->dcmDetected = (pData->sampleCorrFactor < 1.0f) ? 1u : 0u;
            break;

        case PFC_DCM_COMP_VALLEY_EST:
            /* Detect first, then correct only if DCM was actually detected. */
            pData->dcmDetected = dcmByValley;
            pData->sampleCorrFactor = (dcmByValley != 0u)
                                    ? PFC_DcmAverageFactor(pData)
                                    : 1.0f;
            break;

        case PFC_DCM_COMP_OFF:
        default:
            pData->dcmDetected = 0u;
            pData->sampleCorrFactor = 1.0f;
            break;
    }

    pData->averageCurrent = pData->iL * pData->sampleCorrFactor;
}
/**
 * <B> Function: PFC_CurrentControlLoop(PFC_T *pData)  </B>
 * 
 * @brief Function to execute current control loop of PFC
 * @param Pointer to the data structure containing PFC related variables
 * @return none
 * @example
 * <code>
 * PFC_CurrentControlLoop(PFC_T *pData);
 * </code>
 */
inline static void PFC_CurrentControlLoop(PFC_T *pData)
{
    float duty;
    
    /** Ensure PFC current  is not negative.*/ 
    if (pData->iL < 0)
    {
        pData->iL  = 0.0001;
    }
    /** Calculate average current if converter operates in discontinuous
        conduction mode. In continuous conduction mode, measured current is
        used as is ,as average current is obtained. The method is selected by
        pData->sampleCorrectionEnable (PFC_DCM_COMP_T). */
    PFC_CurrentSampleCorrection(pData);

    /* Populate the reference/input fields for logging. The PI update only
     * consumes .error, so these are purely for a self-describing bus. */
    pData->piCurrent.reference = pData->currentReference;
    pData->piCurrent.input     = pData->averageCurrent;
    pData->piCurrent.error = (pData->currentReference - pData->averageCurrent);

    PFC_ControllerPIUpdate(&pData->piCurrent);
    
    /** Calculate duty cycle of PWM that controls PFC in terms of PWM Period */
    duty  = (pData->piCurrent.output * PFC_LOOPTIME_TCY);
    if (duty  > PFC_MAX_DUTY_COUNTS)
    {
        pData->duty = PFC_MAX_DUTY_COUNTS;
        pData->piCurrent.integralOut = PI_I_OUT_MAX;       
    }
    else if (duty  < PFC_MIN_DUTY_COUNTS)
    {
        pData->duty = PFC_MIN_DUTY_COUNTS;
    }
    else
    {
        pData->duty = duty;
    }
}
/**
 * <B> Function: PFC_CurrentRefGenerate(PFC_T *pData)  </B>
 * 
 * @brief Function to calculate current reference for the current control loop
 * @param Pointer to the data structure containing PFC related variables
 * @return none
 * @example
 * <code>
 * PFC_CurrentRefGenerate(PFC_T *pData);
 * </code>
 */
inline static void PFC_CurrentRefGenerate(PFC_T *pData)
{ 
    /** PI Execution - PFC output voltage control.
        Voltage PI is called at the rate specified by VOLTAGE_LOOP_EXE_RATE */
    if (pData->voltLoopExeRate > VOLTAGE_LOOP_EXE_RATE)
    {
        pData->piVoltage.error = pData->piVoltage.reference-pData->vdcAVG.output;

        if((pData->piVoltage.error > 10) || (pData->piVoltage.error < -10 ))
        {
            pData->piVoltage.ki = KI_V /2;
        }
        else
        {
            pData->piVoltage.ki = KI_V;
        }
        /* Record the measurement for a self-describing bus; the reference is
         * already set by the soft-start ramp. */
        pData->piVoltage.input = pData->vdcAVG.output;
        PFC_ControllerPIUpdate(&pData->piVoltage);
        pData->voltLoopExeRate = 0;
    }
    else
    {
       pData->voltLoopExeRate++; 
    }
    
#ifdef PFC_POWER_CONTROL    
    /** Current reference calculation is shown below
        Current reference = (Voltage PI o/p)*(Rectified Vac)*(1/VacRMS^2)*KMUL 
     */ 
        pData->currentReference = (float)((pData->piVoltage.output* pData->rectifiedVac*KMUL)
                            /pData->vacRMS.sqrOutput);
#endif        
    /**  Perform Boundary check of generated current reference */
    if (pData->currentReference > 14.14)
    {
        pData->currentReference = 14.14;
    }
    else if (pData->currentReference < 0)
    {
        pData->currentReference = 0;
    }
}
/**
 * <B> Function: float PFC_SignalRectification(PFC_MEASURE_VOLTAGE_T *pSignal)  </B>
 * 
 * @brief Function to rectify the input AC voltage
 * @param Pointer to the data structure containing measured voltage
 * @return Rectified signal
 * @example
 * <code>
 * PFC_SignalRectification();
 * </code>
 */
float PFC_SignalRectification(PFC_MEASURE_VOLTAGE_T *pSignal)
{   
    float output = pSignal->vac - pSignal->offsetVac;
    
    if(output < 0)
    {
        output = -(output);
    }  
    return(output);
}
/**
 * <B> Function: PFC_SquaredRMSCalculate(PFC_RMS_SQUARE_T *pData,float input)  </B>
 * 
 * @brief Function to calculate RMS value of an input signal
 * @param Pointer to the data structure containing variables related to RMS 
 * calculation, current value of signal  
 * @return none.
 * @example
 * <code>
 * PFC_SquaredRMSCalculate(PFC_RMS_SQUARE_T *pData,float input);
 * </code>
 */
static void PFC_SquaredRMSCalculate(PFC_RMS_SQUARE_T *pData,float input)
{       
    pData->sum += (float) (input*input);
    if(pData->samples < pData->sampleLimit)
    {
       pData->samples++;  
    }
    else
    {
       pData->sqrOutput = (float)((pData->sum/pData->sampleLimit));
       pData->status    = 1;
       pData->samples   = 0;
       pData->sum       = 0;
    }
}
/**
 * <B> Function: PFC_Average(PFC_AVG_T *pData,float input)  </B>
 * 
 * @brief Function to calculate moving average value of an input Signal
 * @param Pointer to the data structure containing variables related to average 
 * calculation, current value of signal 
 * @return none.
 * @example
 * <code>
 * PFC_Average(PFC_AVG_T *pData,float input);
 * </code>
 */
static void PFC_Average(PFC_AVG_T *pData,float input)
{
    pData->sum = pData->sum + input;
    pData->samples++;
    if(pData->samples >= pData->sampleLimit) 
    {
        pData->output  = (float)(pData->sum/pData->sampleLimit);
        pData->status  = 1;
        pData->sum     = 0;
        pData->samples = 0; 
    }
}


/**
 * <B> Function: PFC_FaultCheck(PFC_T *pData)  </B>
 * 
 * @brief Function to check the different fault status
 * @param Pointer to the data structure containing PFC related variables
 * @return none
 * @example
 * <code>
 * PFC_FaultCheck(PFC_T *pData);
 * </code>
 */
void PFC_FaultCheck(PFC_T *pData)
{   
    /*Check the condition for output over voltage*/
    if(pData->vdcAVG.output >= PFC_OUTPUT_OVER_VOLTAGE_LIMIT)
    {
        pData->faultStatus += PFC_FAULT_OP_OV;    
    }
    /*Check the condition for input under voltage*/
    if(pData->vacRMS.sqrOutput < PFC_INPUT_UNDER_VOLTAGE_LIMIT_LO)
    {
        pData->faultStatus += PFC_FAULT_IP_UV;
    }
    /*Check the condition for input over voltage*/
    if(pData->vacRMS.sqrOutput >= PFC_INPUT_OVER_VOLTAGE_LIMIT_HI)
    {
        pData->faultStatus += PFC_FAULT_IP_OV;
    }
}
// </editor-fold>