/* Generated by S-function Builder */
#ifndef _PFC_SF_BUS_H_
#define _PFC_SF_BUS_H_
/* Read only - STARTS */
#ifdef MATLAB_MEX_FILE
#include "tmwtypes.h"
#else
#include "rtwtypes.h"
#endif




#ifndef DEFINED_TYPEDEF_FOR_PFC_MEASURE_VOLTAGE_T_Bus_
#define DEFINED_TYPEDEF_FOR_PFC_MEASURE_VOLTAGE_T_Bus_ 
typedef struct {
  int16_T acVoltage;
  int16_T outputVoltage;
  real32_T vac;
  real32_T offsetVac;
  real32_T vdc;
} PFC_MEASURE_VOLTAGE_T_Bus;
#endif


#ifndef DEFINED_TYPEDEF_FOR_PFC_MEASURE_CURRENT_T_Bus_
#define DEFINED_TYPEDEF_FOR_PFC_MEASURE_CURRENT_T_Bus_ 
typedef struct {
  int16_T inductorCurrent;
  real32_T iL;
  real32_T offset;
  uint16_T counter;
  uint16_T status;
  real32_T sum;
} PFC_MEASURE_CURRENT_T_Bus;
#endif


#ifndef DEFINED_TYPEDEF_FOR_PFC_PI_T_Bus_
#define DEFINED_TYPEDEF_FOR_PFC_PI_T_Bus_ 
typedef struct {
  real32_T output;
  real32_T integralOut;
  real32_T propOut;
  real32_T input;
  real32_T reference;
  real32_T error;
  real32_T kp;
  real32_T ki;
  real32_T kpScale;
  real32_T kiScale;
  real32_T minOutput;
  real32_T maxOutput;
} PFC_PI_T_Bus;
#endif


#ifndef DEFINED_TYPEDEF_FOR_PFC_RMS_SQUARE_T_Bus_
#define DEFINED_TYPEDEF_FOR_PFC_RMS_SQUARE_T_Bus_ 
typedef struct {
  real32_T sqrOutput;
  real32_T sum;
  uint16_T samples;
  uint16_T sampleLimit;
  real32_T peak;
  real32_T peakcheck;
  uint16_T status;
} PFC_RMS_SQUARE_T_Bus;
#endif


#ifndef DEFINED_TYPEDEF_FOR_PFC_AVG_T_Bus_
#define DEFINED_TYPEDEF_FOR_PFC_AVG_T_Bus_ 
typedef struct {
  real32_T sum;
  real32_T output;
  uint16_T scaler;
  uint16_T samples;
  uint16_T sampleLimit;
  uint16_T status;
} PFC_AVG_T_Bus;
#endif


#ifndef DEFINED_TYPEDEF_FOR_PFC_T_Bus_
#define DEFINED_TYPEDEF_FOR_PFC_T_Bus_ 
typedef struct {
  uint32_T duty;
  uint16_T samplePoint;
  real32_T averageCurrent;
  uint16_T rampRate;
  uint16_T voltLoopExeRate;
  real32_T boostDutyRatio;
  real32_T currentReference;
  uint16_T faultStatus;
  uint16_T sampleCorrectionEnable;
  uint16_T dcmDetected;
  real32_T iValleyEst;
  real32_T sampleCorrFactor;
  PFC_AVG_T_Bus vdcAVG;
  PFC_AVG_T_Bus vacAVG;
  PFC_RMS_SQUARE_T_Bus vacRMS;
  PFC_PI_T_Bus piVoltage;
  PFC_PI_T_Bus piCurrent;
  int32_T state;
  PFC_MEASURE_CURRENT_T_Bus pfcCurrent;
  PFC_MEASURE_CURRENT_T_Bus pfcCurrent2;
  PFC_MEASURE_VOLTAGE_T_Bus pfcVoltage;
  real32_T iL;
  real32_T rectifiedVac;
  real32_T outputVdc;
} PFC_T_Bus;
#endif

/* Read only - ENDS */


#endif
