/*
 * File: pfc_sf.c
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand,
 *   you must change it only in the area defined as:
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text'
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Simulink Coder, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Simulink Coder's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  -------------------------------------------------------------------------
 *
 * Created: Thu Jul 23 08:11:62 2026
 */

#define S_FUNCTION_LEVEL               2
#define S_FUNCTION_NAME                pfc_sf

/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS                     4

/* Input Port  0 */
#define IN_PORT_0_NAME                 Vdc_in
#define INPUT_0_DIMS_ND                {1,1}
#define INPUT_0_NUM_ELEMS              1
#define INPUT_0_WIDTH                  1
#define INPUT_DIMS_0_COL               1
#define INPUT_0_DTYPE                  real32_T
#define INPUT_0_COMPLEX                COMPLEX_NO
#define INPUT_0_UNIT                   ""
#define IN_0_BUS_BASED                 0
#define IN_0_BUS_NAME
#define IN_0_DIMS                      1-D
#define INPUT_0_FEEDTHROUGH            1
#define IN_0_ISSIGNED                  1
#define IN_0_WORDLENGTH                8
#define IN_0_FIXPOINTSCALING           1
#define IN_0_FRACTIONLENGTH            3
#define IN_0_BIAS                      0
#define IN_0_SLOPE                     0.125

/* Input Port  1 */
#define IN_PORT_1_NAME                 Vac_in
#define INPUT_1_DIMS_ND                {1,1}
#define INPUT_1_NUM_ELEMS              1
#define INPUT_1_WIDTH                  1
#define INPUT_DIMS_1_COL               1
#define INPUT_1_DTYPE                  real32_T
#define INPUT_1_COMPLEX                COMPLEX_NO
#define INPUT_1_UNIT                   ""
#define IN_1_BUS_BASED                 0
#define IN_1_BUS_NAME
#define IN_1_DIMS                      1-D
#define INPUT_1_FEEDTHROUGH            1
#define IN_1_ISSIGNED                  1
#define IN_1_WORDLENGTH                8
#define IN_1_FIXPOINTSCALING           1
#define IN_1_FRACTIONLENGTH            3
#define IN_1_BIAS                      0
#define IN_1_SLOPE                     0.125

/* Input Port  2 */
#define IN_PORT_2_NAME                 Il_in
#define INPUT_2_DIMS_ND                {1,1}
#define INPUT_2_NUM_ELEMS              1
#define INPUT_2_WIDTH                  1
#define INPUT_DIMS_2_COL               1
#define INPUT_2_DTYPE                  real32_T
#define INPUT_2_COMPLEX                COMPLEX_NO
#define INPUT_2_UNIT                   ""
#define IN_2_BUS_BASED                 0
#define IN_2_BUS_NAME
#define IN_2_DIMS                      1-D
#define INPUT_2_FEEDTHROUGH            1
#define IN_2_ISSIGNED                  1
#define IN_2_WORDLENGTH                8
#define IN_2_FIXPOINTSCALING           1
#define IN_2_FRACTIONLENGTH            3
#define IN_2_BIAS                      0
#define IN_2_SLOPE                     0.125

/* Input Port  3 */
#define IN_PORT_3_NAME                 Iout_in
#define INPUT_3_DIMS_ND                {1,1}
#define INPUT_3_NUM_ELEMS              1
#define INPUT_3_WIDTH                  1
#define INPUT_DIMS_3_COL               1
#define INPUT_3_DTYPE                  real32_T
#define INPUT_3_COMPLEX                COMPLEX_NO
#define INPUT_3_UNIT                   ""
#define IN_3_BUS_BASED                 0
#define IN_3_BUS_NAME
#define IN_3_DIMS                      1-D
#define INPUT_3_FEEDTHROUGH            1
#define IN_3_ISSIGNED                  1
#define IN_3_WORDLENGTH                8
#define IN_3_FIXPOINTSCALING           1
#define IN_3_FRACTIONLENGTH            3
#define IN_3_BIAS                      0
#define IN_3_SLOPE                     0.125
#define NUM_OUTPUTS                    9

/* Output Port  0 */
#define OUT_PORT_0_NAME                state_out
#define OUTPUT_0_DIMS_ND               {1,1}
#define OUTPUT_0_NUM_ELEMS             1
#define OUTPUT_0_WIDTH                 1
#define OUTPUT_DIMS_0_COL              1
#define OUTPUT_0_DTYPE                 uint8_T
#define OUTPUT_0_COMPLEX               COMPLEX_NO
#define OUTPUT_0_UNIT                  ""
#define OUT_0_BUS_BASED                0
#define OUT_0_BUS_NAME
#define OUT_0_DIMS                     1-D
#define OUT_0_ISSIGNED                 1
#define OUT_0_WORDLENGTH               8
#define OUT_0_FIXPOINTSCALING          1
#define OUT_0_FRACTIONLENGTH           3
#define OUT_0_BIAS                     0
#define OUT_0_SLOPE                    0.125

/* Output Port  1 */
#define OUT_PORT_1_NAME                fault_status_out
#define OUTPUT_1_DIMS_ND               {1,1}
#define OUTPUT_1_NUM_ELEMS             1
#define OUTPUT_1_WIDTH                 1
#define OUTPUT_DIMS_1_COL              1
#define OUTPUT_1_DTYPE                 uint16_T
#define OUTPUT_1_COMPLEX               COMPLEX_NO
#define OUTPUT_1_UNIT                  ""
#define OUT_1_BUS_BASED                0
#define OUT_1_BUS_NAME
#define OUT_1_DIMS                     1-D
#define OUT_1_ISSIGNED                 1
#define OUT_1_WORDLENGTH               8
#define OUT_1_FIXPOINTSCALING          1
#define OUT_1_FRACTIONLENGTH           3
#define OUT_1_BIAS                     0
#define OUT_1_SLOPE                    0.125

/* Output Port  2 */
#define OUT_PORT_2_NAME                test1
#define OUTPUT_2_DIMS_ND               {1,1}
#define OUTPUT_2_NUM_ELEMS             1
#define OUTPUT_2_WIDTH                 1
#define OUTPUT_DIMS_2_COL              1
#define OUTPUT_2_DTYPE                 real32_T
#define OUTPUT_2_COMPLEX               COMPLEX_NO
#define OUTPUT_2_UNIT                  ""
#define OUT_2_BUS_BASED                0
#define OUT_2_BUS_NAME
#define OUT_2_DIMS                     1-D
#define OUT_2_ISSIGNED                 1
#define OUT_2_WORDLENGTH               8
#define OUT_2_FIXPOINTSCALING          1
#define OUT_2_FRACTIONLENGTH           3
#define OUT_2_BIAS                     0
#define OUT_2_SLOPE                    0.125

/* Output Port  3 */
#define OUT_PORT_3_NAME                test2
#define OUTPUT_3_DIMS_ND               {1,1}
#define OUTPUT_3_NUM_ELEMS             1
#define OUTPUT_3_WIDTH                 1
#define OUTPUT_DIMS_3_COL              1
#define OUTPUT_3_DTYPE                 real32_T
#define OUTPUT_3_COMPLEX               COMPLEX_NO
#define OUTPUT_3_UNIT                  ""
#define OUT_3_BUS_BASED                0
#define OUT_3_BUS_NAME
#define OUT_3_DIMS                     1-D
#define OUT_3_ISSIGNED                 1
#define OUT_3_WORDLENGTH               8
#define OUT_3_FIXPOINTSCALING          1
#define OUT_3_FRACTIONLENGTH           3
#define OUT_3_BIAS                     0
#define OUT_3_SLOPE                    0.125

/* Output Port  4 */
#define OUT_PORT_4_NAME                pwm_fac
#define OUTPUT_4_DIMS_ND               {1,1}
#define OUTPUT_4_NUM_ELEMS             1
#define OUTPUT_4_WIDTH                 1
#define OUTPUT_DIMS_4_COL              1
#define OUTPUT_4_DTYPE                 real32_T
#define OUTPUT_4_COMPLEX               COMPLEX_NO
#define OUTPUT_4_UNIT                  ""
#define OUT_4_BUS_BASED                0
#define OUT_4_BUS_NAME
#define OUT_4_DIMS                     1-D
#define OUT_4_ISSIGNED                 1
#define OUT_4_WORDLENGTH               8
#define OUT_4_FIXPOINTSCALING          1
#define OUT_4_FRACTIONLENGTH           3
#define OUT_4_BIAS                     0
#define OUT_4_SLOPE                    0.125

/* Output Port  5 */
#define OUT_PORT_5_NAME                pfcParam_piVoltage_out
#define OUTPUT_5_DIMS_ND               {1,3}
#define OUTPUT_5_NUM_ELEMS             3
#define OUTPUT_5_WIDTH                 1
#define OUTPUT_DIMS_5_COL              3
#define OUTPUT_5_DTYPE                 real32_T
#define OUTPUT_5_COMPLEX               COMPLEX_NO
#define OUTPUT_5_UNIT                  ""
#define OUT_5_BUS_BASED                0
#define OUT_5_BUS_NAME
#define OUT_5_DIMS                     2-D
#define OUT_5_ISSIGNED                 1
#define OUT_5_WORDLENGTH               8
#define OUT_5_FIXPOINTSCALING          1
#define OUT_5_FRACTIONLENGTH           3
#define OUT_5_BIAS                     0
#define OUT_5_SLOPE                    0.125

/* Output Port  6 */
#define OUT_PORT_6_NAME                pfcParam_piCurrent_out
#define OUTPUT_6_DIMS_ND               {1,3}
#define OUTPUT_6_NUM_ELEMS             3
#define OUTPUT_6_WIDTH                 1
#define OUTPUT_DIMS_6_COL              3
#define OUTPUT_6_DTYPE                 real32_T
#define OUTPUT_6_COMPLEX               COMPLEX_NO
#define OUTPUT_6_UNIT                  ""
#define OUT_6_BUS_BASED                0
#define OUT_6_BUS_NAME
#define OUT_6_DIMS                     2-D
#define OUT_6_ISSIGNED                 1
#define OUT_6_WORDLENGTH               8
#define OUT_6_FIXPOINTSCALING          1
#define OUT_6_FRACTIONLENGTH           3
#define OUT_6_BIAS                     0
#define OUT_6_SLOPE                    0.125

/* Output Port  7 */
#define OUT_PORT_7_NAME                SiL_Out_PFC_INRUSH_RELAY
#define OUTPUT_7_DIMS_ND               {1,1}
#define OUTPUT_7_NUM_ELEMS             1
#define OUTPUT_7_WIDTH                 1
#define OUTPUT_DIMS_7_COL              1
#define OUTPUT_7_DTYPE                 boolean_T
#define OUTPUT_7_COMPLEX               COMPLEX_NO
#define OUTPUT_7_UNIT                  ""
#define OUT_7_BUS_BASED                0
#define OUT_7_BUS_NAME
#define OUT_7_DIMS                     1-D
#define OUT_7_ISSIGNED                 1
#define OUT_7_WORDLENGTH               8
#define OUT_7_FIXPOINTSCALING          1
#define OUT_7_FRACTIONLENGTH           3
#define OUT_7_BIAS                     0
#define OUT_7_SLOPE                    0.125

/* Output Port  8 */
#define OUT_PORT_8_NAME                pfcParam_out
#define OUTPUT_8_DIMS_ND               {1,1}
#define OUTPUT_8_NUM_ELEMS             1
#define OUTPUT_8_WIDTH                 1
#define OUTPUT_DIMS_8_COL              1
#define OUTPUT_8_DTYPE                 Bus:PFC_Bus
#define OUTPUT_8_COMPLEX               COMPLEX_NO
#define OUTPUT_8_UNIT                  ""
#define OUT_8_BUS_BASED                1
#define OUT_8_BUS_NAME                 PFC_T_Bus
#define OUT_8_DIMS                     1-D
#define OUT_8_ISSIGNED                 1
#define OUT_8_WORDLENGTH               8
#define OUT_8_FIXPOINTSCALING          1
#define OUT_8_FRACTIONLENGTH           3
#define OUT_8_BIAS                     0
#define OUT_8_SLOPE                    0.125
#define NPARAMS                        0
#define SAMPLE_TIME_0                  INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES                0
#define DISC_STATES_IC                 [0]
#define NUM_CONT_STATES                0
#define CONT_STATES_IC                 [0]
#define SFUNWIZ_GENERATE_TLC           1
#define SOURCEFILES                    "__SFB__INC_PATH C:\Users\Andy\Documents\PFC\pfc_1phases_dspic33ak\project\pfc__SFB__INC_PATH C:\Users\Andy\Documents\PFC\pfc_1phases_dspic33ak\SimulinkProject__SFB__INC_PATH c:\Users\Andy\Documents\PFC\pfc_1phases_dspic33ak\project\hal\"
#define PANELINDEX N/A
#define USE_SIMSTRUCT                  0
#define SHOW_COMPILE_STEPS             0
#define CREATE_DEBUG_MEXFILE           0
#define SAVE_CODE_ONLY                 0
#define SFUNWIZ_REVISION               3.0

/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"
#include "pfc_sf_bus.h"

/*
 * Code Generation Environment flag (simulation or standalone target).
 */
static int_T isSimulationTarget;

/* Utility function prototypes. */
static int_T GetRTWEnvironmentMode(SimStruct *S);

/* Macro used to check if Simulation mode is set to accelerator */
#define isBusDWorkPresent              ( ( ( !ssRTWGenIsCodeGen(S) || isSimulationTarget ) && !ssIsExternalSim(S) ) || ssIsRapidAcceleratorActive(S) )

typedef struct {
  int_T offset;
  int_T elemSize;
  int_T numElems;
} busInfoStruct;

extern void pfc_sf_Start_wrapper(void);
extern void pfc_sf_Outputs_wrapper(const real32_T *Vdc_in,
  const real32_T *Vac_in,
  const real32_T *Il_in,
  const real32_T *Iout_in,
  uint8_T *state_out,
  uint16_T *fault_status_out,
  real32_T *test1,
  real32_T *test2,
  real32_T *pwm_fac,
  real32_T *pfcParam_piVoltage_out,
  real32_T *pfcParam_piCurrent_out,
  boolean_T *SiL_Out_PFC_INRUSH_RELAY,
  PFC_T_Bus *pfcParam_out);
extern void pfc_sf_Terminate_wrapper(void);

/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{
  DECL_AND_INIT_DIMSINFO(outputDimsInfo);
  ssSetNumSFcnParams(S, NPARAMS);
  if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
    return;                            /* Parameter mismatch will be reported by Simulink */
  }

  ssSetArrayLayoutForCodeGen(S, SS_COLUMN_MAJOR);
  ssSetOperatingPointCompliance(S, USE_DEFAULT_OPERATING_POINT);
  ssSetNumContStates(S, NUM_CONT_STATES);
  ssSetNumDiscStates(S, NUM_DISC_STATES);
  if (!ssSetNumInputPorts(S, NUM_INPUTS))
    return;

  /* Input Port 0 */
  ssSetInputPortWidth(S, 0, INPUT_0_NUM_ELEMS);
  ssSetInputPortDataType(S, 0, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 0, 1);/*direct input signal access*/

  /* Input Port 1 */
  ssSetInputPortWidth(S, 1, INPUT_1_NUM_ELEMS);
  ssSetInputPortDataType(S, 1, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 1, INPUT_1_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 1, 1);/*direct input signal access*/

  /* Input Port 2 */
  ssSetInputPortWidth(S, 2, INPUT_2_NUM_ELEMS);
  ssSetInputPortDataType(S, 2, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 2, INPUT_2_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 2, INPUT_2_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 2, 1);/*direct input signal access*/

  /* Input Port 3 */
  ssSetInputPortWidth(S, 3, INPUT_3_NUM_ELEMS);
  ssSetInputPortDataType(S, 3, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 3, INPUT_3_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 3, INPUT_3_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 3, 1);/*direct input signal access*/

  /*
   * Configure the Units for Input Ports
   */
  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

#if defined(MATLAB_MEX_FILE)

    UnitId inUnitIdReg;
    ssRegisterUnitFromExpr(S, INPUT_0_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 0, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port Vdc_in of S-Function pfc_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_1_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 1, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port Vac_in of S-Function pfc_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_2_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 2, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port Il_in of S-Function pfc_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_3_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 3, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port Iout_in of S-Function pfc_sf");
      return;
    }

#endif

  }

  if (!ssSetNumOutputPorts(S, NUM_OUTPUTS))
    return;

  /* Output Port 0 */
  ssSetOutputPortWidth(S, 0, OUTPUT_0_NUM_ELEMS);
  ssSetOutputPortDataType(S, 0, SS_UINT8);
  ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);

  /* Output Port 1 */
  ssSetOutputPortWidth(S, 1, OUTPUT_1_NUM_ELEMS);
  ssSetOutputPortDataType(S, 1, SS_UINT16);
  ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);

  /* Output Port 2 */
  ssSetOutputPortWidth(S, 2, OUTPUT_2_NUM_ELEMS);
  ssSetOutputPortDataType(S, 2, SS_SINGLE);
  ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);

  /* Output Port 3 */
  ssSetOutputPortWidth(S, 3, OUTPUT_3_NUM_ELEMS);
  ssSetOutputPortDataType(S, 3, SS_SINGLE);
  ssSetOutputPortComplexSignal(S, 3, OUTPUT_3_COMPLEX);

  /* Output Port 4 */
  ssSetOutputPortWidth(S, 4, OUTPUT_4_NUM_ELEMS);
  ssSetOutputPortDataType(S, 4, SS_SINGLE);
  ssSetOutputPortComplexSignal(S, 4, OUTPUT_4_COMPLEX);

  /* Output Port 5 */
  ssAllowSignalsWithMoreThan2D(S);
  outputDimsInfo.numDims = 2;
  outputDimsInfo.width = OUTPUT_5_NUM_ELEMS;
  int_T out5Dims[] = OUTPUT_5_DIMS_ND;
  outputDimsInfo.dims = out5Dims;
  ssSetOutputPortDimensionInfo(S, 5, &outputDimsInfo);
  ssSetOutputPortDataType(S, 5, SS_SINGLE);
  ssSetOutputPortComplexSignal(S, 5, OUTPUT_5_COMPLEX);

  /* Output Port 6 */
  outputDimsInfo.numDims = 2;
  outputDimsInfo.width = OUTPUT_6_NUM_ELEMS;
  int_T out6Dims[] = OUTPUT_6_DIMS_ND;
  outputDimsInfo.dims = out6Dims;
  ssSetOutputPortDimensionInfo(S, 6, &outputDimsInfo);
  ssSetOutputPortDataType(S, 6, SS_SINGLE);
  ssSetOutputPortComplexSignal(S, 6, OUTPUT_6_COMPLEX);

  /* Output Port 7 */
  ssSetOutputPortWidth(S, 7, OUTPUT_7_NUM_ELEMS);
  ssSetOutputPortDataType(S, 7, SS_BOOLEAN);
  ssSetOutputPortComplexSignal(S, 7, OUTPUT_7_COMPLEX);

  /* Output Port 8 */

  /* Register PFC_T_Bus datatype for Output port 8 */
#if defined(MATLAB_MEX_FILE)

  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
    DTypeId dataTypeIdReg;
    ssRegisterTypeFromNamedObject(S, "PFC_T_Bus", &dataTypeIdReg);
    if (dataTypeIdReg == INVALID_DTYPE_ID)
      return;
    ssSetOutputPortDataType(S, 8, dataTypeIdReg);
  }

#endif

  ssSetOutputPortWidth(S, 8, OUTPUT_8_NUM_ELEMS);
  ssSetBusOutputObjectName(S, 8, (void *) "PFC_T_Bus");
  ssSetOutputPortComplexSignal(S, 8, OUTPUT_8_COMPLEX);
  ssSetBusOutputAsStruct(S, 8,OUT_8_BUS_BASED);
  ssSetOutputPortBusMode(S, 8, SL_BUS_MODE);

  /*
   * Configure the Units for Output Ports
   */
  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

#if defined(MATLAB_MEX_FILE)

    UnitId outUnitIdReg;
    ssRegisterUnitFromExpr(S, OUTPUT_0_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 0, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port state_out of S-Function pfc_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_1_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 1, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port fault_status_out of S-Function pfc_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_2_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 2, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port test1 of S-Function pfc_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_3_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 3, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port test2 of S-Function pfc_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_4_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 4, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port pwm_fac of S-Function pfc_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_5_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 5, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port pfcParam_piVoltage_out of S-Function pfc_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_6_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 6, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port pfcParam_piCurrent_out of S-Function pfc_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_7_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 7, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port SiL_Out_PFC_INRUSH_RELAY of S-Function pfc_sf");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_8_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 8, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port pfcParam_out of S-Function pfc_sf");
      return;
    }

#endif

  }

  if (ssRTWGenIsCodeGen(S)) {
    isSimulationTarget = GetRTWEnvironmentMode(S);
    if (isSimulationTarget == -1) {
      ssSetLocalErrorStatus(S,
                            " Unable to determine a valid code generation environment mode");
      return;
    }

    isSimulationTarget |= ssRTWGenIsModelReferenceSimTarget(S);
  }

  /* Set the number of dworks */
  if (!ssSetNumDWork(S, 1))
    return;

  /*
   * Configure the dwork 0 (pfcParam_outBUS)
   */
#if defined(MATLAB_MEX_FILE)

  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
    DTypeId dataTypeIdReg;
    ssRegisterTypeFromNamedObject(S, "PFC_T_Bus", &dataTypeIdReg);
    if (dataTypeIdReg == INVALID_DTYPE_ID)
      return;
    if (isBusDWorkPresent) {
      ssSetDWorkDataType(S, 0, dataTypeIdReg);
    } else {
      ssSetDWorkDataType(S, 0, SS_POINTER);
    }
  }

#endif

  ssSetDWorkUsageType(S, 0, SS_DWORK_USED_AS_DWORK);
  ssSetDWorkName(S, 0, "pfcParam_outBUS");
  ssSetDWorkWidth(S, 0, DYNAMICALLY_SIZED);
  ssSetDWorkComplexSignal(S, 0, COMPLEX_NO);
  ssSetNumPWork(S, 0);
  ssSetNumSampleTimes(S, 1);
  ssSetNumRWork(S, 0);
  ssSetNumIWork(S, 0);
  ssSetNumModes(S, 0);
  ssSetNumNonsampledZCs(S, 0);
  ssSetSimulinkVersionGeneratedIn(S, "26.1");

  /* Take care when specifying exception free code - see sfuntmpl_doc.c */
  ssSetRuntimeThreadSafetyCompliance(S, RUNTIME_THREAD_SAFETY_COMPLIANCE_FALSE);
  ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                   SS_OPTION_USE_TLC_WITH_ACCELERATOR |
                   SS_OPTION_WORKS_WITH_CODE_REUSE));
}

#if defined(MATLAB_MEX_FILE)
#define MDL_SET_INPUT_PORT_DIMENSION_INFO

static void mdlSetInputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetInputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

#define MDL_SET_OUTPUT_PORT_DIMENSION_INFO
#if defined(MDL_SET_OUTPUT_PORT_DIMENSION_INFO)

static void mdlSetOutputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetOutputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

#define MDL_SET_DEFAULT_PORT_DIMENSION_INFO

static void mdlSetDefaultPortDimensionInfo(SimStruct *S)
{
  DECL_AND_INIT_DIMSINFO(portDimsInfo);
  int_T dims[2];

  /* Setting default dimensions for output port 5 */
  portDimsInfo.width = OUTPUT_5_NUM_ELEMS;
  dims[0] = OUTPUT_5_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetOutputPortNumDimensions(S, 5) == (-1)) {
    ssSetOutputPortDimensionInfo(S, 5, &portDimsInfo);
  }

  /* Setting default dimensions for output port 6 */
  portDimsInfo.width = OUTPUT_6_NUM_ELEMS;
  dims[0] = OUTPUT_6_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetOutputPortNumDimensions(S, 6) == (-1)) {
    ssSetOutputPortDimensionInfo(S, 6, &portDimsInfo);
  }

  return;
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
  ssSetSampleTime(S, 0, SAMPLE_TIME_0);
  ssSetModelReferenceSampleTimeDefaultInheritance(S);
  ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE

static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetInputPortDataType(S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE

static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES

static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType(S, 0, SS_DOUBLE);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

#define MDL_SET_WORK_WIDTHS
#if defined(MDL_SET_WORK_WIDTHS) && defined(MATLAB_MEX_FILE)

static void mdlSetWorkWidths(SimStruct *S)
{
  /* Set the width of DWork(s) used for marshalling the IOs */
  if (isBusDWorkPresent) {
    /* Update dwork 0 */
    ssSetDWorkWidth(S, 0, ssGetOutputPortWidth(S, 8));
  } else {
    ssSetDWorkWidth(S, 0, 1);
  }
}

#endif

#define MDL_START                                                /* Change to #undef to remove function */
#if defined(MDL_START)

/* Function: mdlStart =======================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{
  /* Bus Information */
  slDataTypeAccess *dta = ssGetDataTypeAccess(S);
  const char *bpath = ssGetPath(S);
  DTypeId PFC_AVG_T_BusId = ssGetDataTypeId(S,"PFC_AVG_T_Bus");
  DTypeId PFC_MEASURE_CURRENT_T_BusId = ssGetDataTypeId(S,
    "PFC_MEASURE_CURRENT_T_Bus");
  DTypeId PFC_MEASURE_VOLTAGE_T_BusId = ssGetDataTypeId(S,
    "PFC_MEASURE_VOLTAGE_T_Bus");
  DTypeId PFC_PI_T_BusId = ssGetDataTypeId(S,"PFC_PI_T_Bus");
  DTypeId PFC_RMS_SQUARE_T_BusId = ssGetDataTypeId(S,"PFC_RMS_SQUARE_T_Bus");
  DTypeId PFC_T_BusId = ssGetDataTypeId(S,"PFC_T_Bus");
  busInfoStruct *busInfo = (busInfoStruct *)malloc(85*sizeof(busInfoStruct));
  if (busInfo==NULL) {
    ssSetLocalErrorStatus(S, "Memory allocation failure");
    return;
  }

  /*offsets info for all unique bus structures*/
  busInfo[0].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 0);
  busInfo[0].elemSize = dtaGetDataTypeSize(dta, bpath, SS_UINT32);
  busInfo[0].numElems = 1;
  busInfo[1].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 1);
  busInfo[1].elemSize = dtaGetDataTypeSize(dta, bpath, SS_UINT16);
  busInfo[1].numElems = 1;
  busInfo[2].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 2);
  busInfo[2].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[2].numElems = 1;
  busInfo[3].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 3);
  busInfo[3].elemSize = dtaGetDataTypeSize(dta, bpath, SS_UINT16);
  busInfo[3].numElems = 1;
  busInfo[4].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 4);
  busInfo[4].elemSize = dtaGetDataTypeSize(dta, bpath, SS_UINT16);
  busInfo[4].numElems = 1;
  busInfo[5].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 5);
  busInfo[5].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[5].numElems = 1;
  busInfo[6].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 6);
  busInfo[6].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[6].numElems = 1;
  busInfo[7].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 7);
  busInfo[7].elemSize = dtaGetDataTypeSize(dta, bpath, SS_UINT16);
  busInfo[7].numElems = 1;
  busInfo[8].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 8);
  busInfo[8].elemSize = dtaGetDataTypeSize(dta, bpath, SS_UINT16);
  busInfo[8].numElems = 1;
  busInfo[9].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 9);
  busInfo[9].elemSize = dtaGetDataTypeSize(dta, bpath, SS_UINT16);
  busInfo[9].numElems = 1;
  busInfo[10].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 10);
  busInfo[10].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[10].numElems = 1;
  busInfo[11].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 11);
  busInfo[11].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[11].numElems = 1;
  busInfo[12].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 12);
  busInfo[12].elemSize = dtaGetDataTypeSize(dta, bpath, PFC_AVG_T_BusId);
  busInfo[12].numElems = 1;
  busInfo[13].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_AVG_T_BusId,
    0);
  busInfo[13].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[13].numElems = 1;
  busInfo[14].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_AVG_T_BusId,
    1);
  busInfo[14].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[14].numElems = 1;
  busInfo[15].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_AVG_T_BusId,
    2);
  busInfo[15].elemSize = dtaGetDataTypeSize(dta, bpath, SS_UINT16);
  busInfo[15].numElems = 1;
  busInfo[16].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_AVG_T_BusId,
    3);
  busInfo[16].elemSize = dtaGetDataTypeSize(dta, bpath, SS_UINT16);
  busInfo[16].numElems = 1;
  busInfo[17].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_AVG_T_BusId,
    4);
  busInfo[17].elemSize = dtaGetDataTypeSize(dta, bpath, SS_UINT16);
  busInfo[17].numElems = 1;
  busInfo[18].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_AVG_T_BusId,
    5);
  busInfo[18].elemSize = dtaGetDataTypeSize(dta, bpath, SS_UINT16);
  busInfo[18].numElems = 1;
  busInfo[19].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 13);
  busInfo[19].elemSize = dtaGetDataTypeSize(dta, bpath, PFC_AVG_T_BusId);
  busInfo[19].numElems = 1;
  busInfo[26].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 14);
  busInfo[26].elemSize = dtaGetDataTypeSize(dta, bpath, PFC_RMS_SQUARE_T_BusId);
  busInfo[26].numElems = 1;
  busInfo[27].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_RMS_SQUARE_T_BusId, 0);
  busInfo[27].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[27].numElems = 1;
  busInfo[28].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_RMS_SQUARE_T_BusId, 1);
  busInfo[28].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[28].numElems = 1;
  busInfo[29].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_RMS_SQUARE_T_BusId, 2);
  busInfo[29].elemSize = dtaGetDataTypeSize(dta, bpath, SS_UINT16);
  busInfo[29].numElems = 1;
  busInfo[30].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_RMS_SQUARE_T_BusId, 3);
  busInfo[30].elemSize = dtaGetDataTypeSize(dta, bpath, SS_UINT16);
  busInfo[30].numElems = 1;
  busInfo[31].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_RMS_SQUARE_T_BusId, 4);
  busInfo[31].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[31].numElems = 1;
  busInfo[32].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_RMS_SQUARE_T_BusId, 5);
  busInfo[32].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[32].numElems = 1;
  busInfo[33].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_RMS_SQUARE_T_BusId, 6);
  busInfo[33].elemSize = dtaGetDataTypeSize(dta, bpath, SS_UINT16);
  busInfo[33].numElems = 1;
  busInfo[34].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 15);
  busInfo[34].elemSize = dtaGetDataTypeSize(dta, bpath, PFC_PI_T_BusId);
  busInfo[34].numElems = 1;
  busInfo[35].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_PI_T_BusId, 0);
  busInfo[35].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[35].numElems = 1;
  busInfo[36].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_PI_T_BusId, 1);
  busInfo[36].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[36].numElems = 1;
  busInfo[37].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_PI_T_BusId, 2);
  busInfo[37].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[37].numElems = 1;
  busInfo[38].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_PI_T_BusId, 3);
  busInfo[38].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[38].numElems = 1;
  busInfo[39].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_PI_T_BusId, 4);
  busInfo[39].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[39].numElems = 1;
  busInfo[40].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_PI_T_BusId, 5);
  busInfo[40].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[40].numElems = 1;
  busInfo[41].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_PI_T_BusId, 6);
  busInfo[41].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[41].numElems = 1;
  busInfo[42].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_PI_T_BusId, 7);
  busInfo[42].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[42].numElems = 1;
  busInfo[43].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_PI_T_BusId, 8);
  busInfo[43].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[43].numElems = 1;
  busInfo[44].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_PI_T_BusId, 9);
  busInfo[44].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[44].numElems = 1;
  busInfo[45].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_PI_T_BusId,
    10);
  busInfo[45].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[45].numElems = 1;
  busInfo[46].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_PI_T_BusId,
    11);
  busInfo[46].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[46].numElems = 1;
  busInfo[47].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 16);
  busInfo[47].elemSize = dtaGetDataTypeSize(dta, bpath, PFC_PI_T_BusId);
  busInfo[47].numElems = 1;
  busInfo[60].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 17);
  busInfo[60].elemSize = dtaGetDataTypeSize(dta, bpath, SS_INT32);
  busInfo[60].numElems = 1;
  busInfo[61].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 18);
  busInfo[61].elemSize = dtaGetDataTypeSize(dta, bpath,
    PFC_MEASURE_CURRENT_T_BusId);
  busInfo[61].numElems = 1;
  busInfo[62].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_MEASURE_CURRENT_T_BusId, 0);
  busInfo[62].elemSize = dtaGetDataTypeSize(dta, bpath, SS_INT16);
  busInfo[62].numElems = 1;
  busInfo[63].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_MEASURE_CURRENT_T_BusId, 1);
  busInfo[63].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[63].numElems = 1;
  busInfo[64].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_MEASURE_CURRENT_T_BusId, 2);
  busInfo[64].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[64].numElems = 1;
  busInfo[65].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_MEASURE_CURRENT_T_BusId, 3);
  busInfo[65].elemSize = dtaGetDataTypeSize(dta, bpath, SS_UINT16);
  busInfo[65].numElems = 1;
  busInfo[66].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_MEASURE_CURRENT_T_BusId, 4);
  busInfo[66].elemSize = dtaGetDataTypeSize(dta, bpath, SS_UINT16);
  busInfo[66].numElems = 1;
  busInfo[67].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_MEASURE_CURRENT_T_BusId, 5);
  busInfo[67].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[67].numElems = 1;
  busInfo[68].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 19);
  busInfo[68].elemSize = dtaGetDataTypeSize(dta, bpath,
    PFC_MEASURE_CURRENT_T_BusId);
  busInfo[68].numElems = 1;
  busInfo[75].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 20);
  busInfo[75].elemSize = dtaGetDataTypeSize(dta, bpath,
    PFC_MEASURE_VOLTAGE_T_BusId);
  busInfo[75].numElems = 1;
  busInfo[76].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_MEASURE_VOLTAGE_T_BusId, 0);
  busInfo[76].elemSize = dtaGetDataTypeSize(dta, bpath, SS_INT16);
  busInfo[76].numElems = 1;
  busInfo[77].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_MEASURE_VOLTAGE_T_BusId, 1);
  busInfo[77].elemSize = dtaGetDataTypeSize(dta, bpath, SS_INT16);
  busInfo[77].numElems = 1;
  busInfo[78].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_MEASURE_VOLTAGE_T_BusId, 2);
  busInfo[78].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[78].numElems = 1;
  busInfo[79].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_MEASURE_VOLTAGE_T_BusId, 3);
  busInfo[79].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[79].numElems = 1;
  busInfo[80].offset = dtaGetDataTypeElementOffset(dta, bpath,
    PFC_MEASURE_VOLTAGE_T_BusId, 4);
  busInfo[80].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[80].numElems = 1;
  busInfo[81].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 21);
  busInfo[81].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[81].numElems = 1;
  busInfo[82].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 22);
  busInfo[82].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[82].numElems = 1;
  busInfo[83].offset = dtaGetDataTypeElementOffset(dta, bpath, PFC_T_BusId, 23);
  busInfo[83].elemSize = dtaGetDataTypeSize(dta, bpath, SS_SINGLE);
  busInfo[83].numElems = 1;
  busInfo[84].elemSize = dtaGetDataTypeSize(dta, bpath, PFC_T_BusId);
  busInfo[84].numElems = ssGetOutputPortWidth(S, 8);
  ssSetUserData(S, busInfo);

  /* Allocate memory for arrays or nested arrays of buses DWork pointers */
  pfc_sf_Start_wrapper();
}

#endif                                 /*  MDL_START */

/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
  const real32_T *Vdc_in = (real32_T *) ssGetInputPortRealSignal(S, 0);
  const real32_T *Vac_in = (real32_T *) ssGetInputPortRealSignal(S, 1);
  const real32_T *Il_in = (real32_T *) ssGetInputPortRealSignal(S, 2);
  const real32_T *Iout_in = (real32_T *) ssGetInputPortRealSignal(S, 3);
  uint8_T *state_out = (uint8_T *) ssGetOutputPortRealSignal(S, 0);
  uint16_T *fault_status_out = (uint16_T *) ssGetOutputPortRealSignal(S, 1);
  real32_T *test1 = (real32_T *) ssGetOutputPortRealSignal(S, 2);
  real32_T *test2 = (real32_T *) ssGetOutputPortRealSignal(S, 3);
  real32_T *pwm_fac = (real32_T *) ssGetOutputPortRealSignal(S, 4);
  real32_T *pfcParam_piVoltage_out = (real32_T *) ssGetOutputPortRealSignal(S, 5);
  real32_T *pfcParam_piCurrent_out = (real32_T *) ssGetOutputPortRealSignal(S, 6);
  boolean_T *SiL_Out_PFC_INRUSH_RELAY = (boolean_T *) ssGetOutputPortRealSignal
    (S, 7);
  char *pfcParam_out = (char *) ssGetOutputPortSignal(S, 8);
  busInfoStruct* busInfo = (busInfoStruct *) ssGetUserData(S);

  /* Temporary bus copy declarations */
  PFC_T_Bus _pfcParam_outBUS;
  slDataTypeAccess *dta = ssGetDataTypeAccess(S);
  const char *bpath = ssGetPath(S);

  /*Copy from Simulink to bus structure*/
  pfc_sf_Outputs_wrapper(Vdc_in, Vac_in, Il_in, Iout_in, state_out,
    fault_status_out, test1, test2, pwm_fac, pfcParam_piVoltage_out,
    pfcParam_piCurrent_out, SiL_Out_PFC_INRUSH_RELAY, &_pfcParam_outBUS);

  /*Copy from bus structure to Simulink*/

  /*Copy from _pfcParam_outBUS to Simulink for Output port 8*/
  *((uint32_T*)((char *) pfcParam_out + busInfo[0].offset)) = (_pfcParam_outBUS)
    .duty;
  *((uint16_T*)((char *) pfcParam_out + busInfo[1].offset)) = (_pfcParam_outBUS)
    .samplePoint;
  *((real32_T*)((char *) pfcParam_out + busInfo[2].offset)) = (_pfcParam_outBUS)
    .averageCurrent;
  *((uint16_T*)((char *) pfcParam_out + busInfo[3].offset)) = (_pfcParam_outBUS)
    .rampRate;
  *((uint16_T*)((char *) pfcParam_out + busInfo[4].offset)) = (_pfcParam_outBUS)
    .voltLoopExeRate;
  *((real32_T*)((char *) pfcParam_out + busInfo[5].offset)) = (_pfcParam_outBUS)
    .boostDutyRatio;
  *((real32_T*)((char *) pfcParam_out + busInfo[6].offset)) = (_pfcParam_outBUS)
    .currentReference;
  *((uint16_T*)((char *) pfcParam_out + busInfo[7].offset)) = (_pfcParam_outBUS)
    .faultStatus;
  *((uint16_T*)((char *) pfcParam_out + busInfo[8].offset)) = (_pfcParam_outBUS)
    .sampleCorrectionEnable;
  *((uint16_T*)((char *) pfcParam_out + busInfo[9].offset)) = (_pfcParam_outBUS)
    .dcmDetected;
  *((real32_T*)((char *) pfcParam_out + busInfo[10].offset)) = (_pfcParam_outBUS)
    .iValleyEst;
  *((real32_T*)((char *) pfcParam_out + busInfo[11].offset)) = (_pfcParam_outBUS)
    .sampleCorrFactor;
  *((real32_T*)((char *) pfcParam_out + busInfo[12].offset + busInfo[13].offset))
    = (_pfcParam_outBUS).vdcAVG.sum;
  *((real32_T*)((char *) pfcParam_out + busInfo[12].offset + busInfo[14].offset))
    = (_pfcParam_outBUS).vdcAVG.output;
  *((uint16_T*)((char *) pfcParam_out + busInfo[12].offset + busInfo[15].offset))
    = (_pfcParam_outBUS).vdcAVG.scaler;
  *((uint16_T*)((char *) pfcParam_out + busInfo[12].offset + busInfo[16].offset))
    = (_pfcParam_outBUS).vdcAVG.samples;
  *((uint16_T*)((char *) pfcParam_out + busInfo[12].offset + busInfo[17].offset))
    = (_pfcParam_outBUS).vdcAVG.sampleLimit;
  *((uint16_T*)((char *) pfcParam_out + busInfo[12].offset + busInfo[18].offset))
    = (_pfcParam_outBUS).vdcAVG.status;
  *((real32_T*)((char *) pfcParam_out + busInfo[19].offset + busInfo[13].offset))
    = (_pfcParam_outBUS).vacAVG.sum;
  *((real32_T*)((char *) pfcParam_out + busInfo[19].offset + busInfo[14].offset))
    = (_pfcParam_outBUS).vacAVG.output;
  *((uint16_T*)((char *) pfcParam_out + busInfo[19].offset + busInfo[15].offset))
    = (_pfcParam_outBUS).vacAVG.scaler;
  *((uint16_T*)((char *) pfcParam_out + busInfo[19].offset + busInfo[16].offset))
    = (_pfcParam_outBUS).vacAVG.samples;
  *((uint16_T*)((char *) pfcParam_out + busInfo[19].offset + busInfo[17].offset))
    = (_pfcParam_outBUS).vacAVG.sampleLimit;
  *((uint16_T*)((char *) pfcParam_out + busInfo[19].offset + busInfo[18].offset))
    = (_pfcParam_outBUS).vacAVG.status;
  *((real32_T*)((char *) pfcParam_out + busInfo[26].offset + busInfo[27].offset))
    = (_pfcParam_outBUS).vacRMS.sqrOutput;
  *((real32_T*)((char *) pfcParam_out + busInfo[26].offset + busInfo[28].offset))
    = (_pfcParam_outBUS).vacRMS.sum;
  *((uint16_T*)((char *) pfcParam_out + busInfo[26].offset + busInfo[29].offset))
    = (_pfcParam_outBUS).vacRMS.samples;
  *((uint16_T*)((char *) pfcParam_out + busInfo[26].offset + busInfo[30].offset))
    = (_pfcParam_outBUS).vacRMS.sampleLimit;
  *((real32_T*)((char *) pfcParam_out + busInfo[26].offset + busInfo[31].offset))
    = (_pfcParam_outBUS).vacRMS.peak;
  *((real32_T*)((char *) pfcParam_out + busInfo[26].offset + busInfo[32].offset))
    = (_pfcParam_outBUS).vacRMS.peakcheck;
  *((uint16_T*)((char *) pfcParam_out + busInfo[26].offset + busInfo[33].offset))
    = (_pfcParam_outBUS).vacRMS.status;
  *((real32_T*)((char *) pfcParam_out + busInfo[34].offset + busInfo[35].offset))
    = (_pfcParam_outBUS).piVoltage.output;
  *((real32_T*)((char *) pfcParam_out + busInfo[34].offset + busInfo[36].offset))
    = (_pfcParam_outBUS).piVoltage.integralOut;
  *((real32_T*)((char *) pfcParam_out + busInfo[34].offset + busInfo[37].offset))
    = (_pfcParam_outBUS).piVoltage.propOut;
  *((real32_T*)((char *) pfcParam_out + busInfo[34].offset + busInfo[38].offset))
    = (_pfcParam_outBUS).piVoltage.input;
  *((real32_T*)((char *) pfcParam_out + busInfo[34].offset + busInfo[39].offset))
    = (_pfcParam_outBUS).piVoltage.reference;
  *((real32_T*)((char *) pfcParam_out + busInfo[34].offset + busInfo[40].offset))
    = (_pfcParam_outBUS).piVoltage.error;
  *((real32_T*)((char *) pfcParam_out + busInfo[34].offset + busInfo[41].offset))
    = (_pfcParam_outBUS).piVoltage.kp;
  *((real32_T*)((char *) pfcParam_out + busInfo[34].offset + busInfo[42].offset))
    = (_pfcParam_outBUS).piVoltage.ki;
  *((real32_T*)((char *) pfcParam_out + busInfo[34].offset + busInfo[43].offset))
    = (_pfcParam_outBUS).piVoltage.kpScale;
  *((real32_T*)((char *) pfcParam_out + busInfo[34].offset + busInfo[44].offset))
    = (_pfcParam_outBUS).piVoltage.kiScale;
  *((real32_T*)((char *) pfcParam_out + busInfo[34].offset + busInfo[45].offset))
    = (_pfcParam_outBUS).piVoltage.minOutput;
  *((real32_T*)((char *) pfcParam_out + busInfo[34].offset + busInfo[46].offset))
    = (_pfcParam_outBUS).piVoltage.maxOutput;
  *((real32_T*)((char *) pfcParam_out + busInfo[47].offset + busInfo[35].offset))
    = (_pfcParam_outBUS).piCurrent.output;
  *((real32_T*)((char *) pfcParam_out + busInfo[47].offset + busInfo[36].offset))
    = (_pfcParam_outBUS).piCurrent.integralOut;
  *((real32_T*)((char *) pfcParam_out + busInfo[47].offset + busInfo[37].offset))
    = (_pfcParam_outBUS).piCurrent.propOut;
  *((real32_T*)((char *) pfcParam_out + busInfo[47].offset + busInfo[38].offset))
    = (_pfcParam_outBUS).piCurrent.input;
  *((real32_T*)((char *) pfcParam_out + busInfo[47].offset + busInfo[39].offset))
    = (_pfcParam_outBUS).piCurrent.reference;
  *((real32_T*)((char *) pfcParam_out + busInfo[47].offset + busInfo[40].offset))
    = (_pfcParam_outBUS).piCurrent.error;
  *((real32_T*)((char *) pfcParam_out + busInfo[47].offset + busInfo[41].offset))
    = (_pfcParam_outBUS).piCurrent.kp;
  *((real32_T*)((char *) pfcParam_out + busInfo[47].offset + busInfo[42].offset))
    = (_pfcParam_outBUS).piCurrent.ki;
  *((real32_T*)((char *) pfcParam_out + busInfo[47].offset + busInfo[43].offset))
    = (_pfcParam_outBUS).piCurrent.kpScale;
  *((real32_T*)((char *) pfcParam_out + busInfo[47].offset + busInfo[44].offset))
    = (_pfcParam_outBUS).piCurrent.kiScale;
  *((real32_T*)((char *) pfcParam_out + busInfo[47].offset + busInfo[45].offset))
    = (_pfcParam_outBUS).piCurrent.minOutput;
  *((real32_T*)((char *) pfcParam_out + busInfo[47].offset + busInfo[46].offset))
    = (_pfcParam_outBUS).piCurrent.maxOutput;
  *((int32_T*)((char *) pfcParam_out + busInfo[60].offset)) = (_pfcParam_outBUS)
    .state;
  *((int16_T*)((char *) pfcParam_out + busInfo[61].offset + busInfo[62].offset))
    = (_pfcParam_outBUS).pfcCurrent.inductorCurrent;
  *((real32_T*)((char *) pfcParam_out + busInfo[61].offset + busInfo[63].offset))
    = (_pfcParam_outBUS).pfcCurrent.iL;
  *((real32_T*)((char *) pfcParam_out + busInfo[61].offset + busInfo[64].offset))
    = (_pfcParam_outBUS).pfcCurrent.offset;
  *((uint16_T*)((char *) pfcParam_out + busInfo[61].offset + busInfo[65].offset))
    = (_pfcParam_outBUS).pfcCurrent.counter;
  *((uint16_T*)((char *) pfcParam_out + busInfo[61].offset + busInfo[66].offset))
    = (_pfcParam_outBUS).pfcCurrent.status;
  *((real32_T*)((char *) pfcParam_out + busInfo[61].offset + busInfo[67].offset))
    = (_pfcParam_outBUS).pfcCurrent.sum;
  *((int16_T*)((char *) pfcParam_out + busInfo[68].offset + busInfo[62].offset))
    = (_pfcParam_outBUS).pfcCurrent2.inductorCurrent;
  *((real32_T*)((char *) pfcParam_out + busInfo[68].offset + busInfo[63].offset))
    = (_pfcParam_outBUS).pfcCurrent2.iL;
  *((real32_T*)((char *) pfcParam_out + busInfo[68].offset + busInfo[64].offset))
    = (_pfcParam_outBUS).pfcCurrent2.offset;
  *((uint16_T*)((char *) pfcParam_out + busInfo[68].offset + busInfo[65].offset))
    = (_pfcParam_outBUS).pfcCurrent2.counter;
  *((uint16_T*)((char *) pfcParam_out + busInfo[68].offset + busInfo[66].offset))
    = (_pfcParam_outBUS).pfcCurrent2.status;
  *((real32_T*)((char *) pfcParam_out + busInfo[68].offset + busInfo[67].offset))
    = (_pfcParam_outBUS).pfcCurrent2.sum;
  *((int16_T*)((char *) pfcParam_out + busInfo[75].offset + busInfo[76].offset))
    = (_pfcParam_outBUS).pfcVoltage.acVoltage;
  *((int16_T*)((char *) pfcParam_out + busInfo[75].offset + busInfo[77].offset))
    = (_pfcParam_outBUS).pfcVoltage.outputVoltage;
  *((real32_T*)((char *) pfcParam_out + busInfo[75].offset + busInfo[78].offset))
    = (_pfcParam_outBUS).pfcVoltage.vac;
  *((real32_T*)((char *) pfcParam_out + busInfo[75].offset + busInfo[79].offset))
    = (_pfcParam_outBUS).pfcVoltage.offsetVac;
  *((real32_T*)((char *) pfcParam_out + busInfo[75].offset + busInfo[80].offset))
    = (_pfcParam_outBUS).pfcVoltage.vdc;
  *((real32_T*)((char *) pfcParam_out + busInfo[81].offset)) = (_pfcParam_outBUS)
    .iL;
  *((real32_T*)((char *) pfcParam_out + busInfo[82].offset)) = (_pfcParam_outBUS)
    .rectifiedVac;
  *((real32_T*)((char *) pfcParam_out + busInfo[83].offset)) = (_pfcParam_outBUS)
    .outputVdc;
}

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
  pfc_sf_Terminate_wrapper();

  /* Free stored bus information */
  busInfoStruct *busInfo = (busInfoStruct *) ssGetUserData(S);
  if (busInfo != NULL) {
    free(busInfo);
  }

  if (!isBusDWorkPresent) {
  }
}

static int_T GetRTWEnvironmentMode(SimStruct *S)
{
  int_T status = -1;
  mxArray *plhs[1];
  mxArray *prhs[1];
  mxArray * err;

  /*
   * Get the name of the Simulink block diagram
   */
  prhs[0] = mxCreateString(ssGetBlockDiagramName(S));
  plhs[0] = NULL;

  /*
   * Call "isSimulationTarget = rtwenvironmentmode(modelName)" in MATLAB
   */
  err = mexCallMATLABWithTrap(1, plhs, 1, prhs, "rtwenvironmentmode");
  mxDestroyArray(prhs[0]);

  /*
   * Set the error status if an error occurred
   */
  if (err) {
    if (plhs[0]) {
      mxDestroyArray(plhs[0]);
      plhs[0] = NULL;
    }

    ssSetLocalErrorStatus(S,
                          "Unknown error during call to 'rtwenvironmentmode'.");
    return -1;
  }

  /*
   * Get the value returned by rtwenvironmentmode(modelName)
   */
  if (plhs[0]) {
    status = (int_T) (mxGetScalar(plhs[0]) != 0);
    mxDestroyArray(plhs[0]);
    plhs[0] = NULL;
  }

  return (status);
}

#ifdef MATLAB_MEX_FILE                 /* Is this file being compiled as a MEX-file? */
#include "simulink.c"                  /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"                   /* Code generation registration function */
#endif
